import { normalizeAppLocale, type AppLocale } from '../../i18n'
import type { ContractAdjustmentIndex, ContractStatus } from '../../lib/api/leaseContracts'

const contractCopies = {
  'en-US': {
    detail: {
      actions: {
        back: 'Back to contracts',
        edit: 'Edit contract',
      },
      audit: {
        archivedAt: 'Archived at',
        createdAt: 'Created at',
        updatedAt: 'Updated at',
      },
      documentsTitle: 'Document links',
      emptyRelationship: 'This relationship will appear here when connected.',
      error: 'Could not load contract details.',
      labels: {
        adjustment: 'Adjustment',
        deposit: 'Deposit',
        discount: 'Discount notes',
        dueDay: 'Due day',
        endDate: 'End date',
        monthlyRent: 'Monthly rent',
        notes: 'Notes',
        penalty: 'Penalty notes',
        primaryResident: 'Primary resident',
        property: 'Property',
        residents: 'Residents',
        startDate: 'Start date',
        status: 'Status',
      },
      loading: 'Loading contract details...',
      noNotes: 'No notes registered.',
      pageDescription: 'Review terms, residents, property, documents, and related records.',
      relationshipTitle: 'Relationships',
      summaryTitle: 'Contract summary',
    },
    form: {
      adjustmentIndex: 'Adjustment index',
      adjustmentIntervalMonths: 'Adjustment interval months',
      adjustmentRequired: 'Select an adjustment index.',
      cancel: 'Cancel',
      dateRangeRequired: 'End date cannot be before start date.',
      depositAmount: 'Deposit',
      discountNotes: 'Discount notes',
      documentSection: 'Documents',
      documentSummary: 'Signed contract links are managed in Documents.',
      dueDay: 'Due day',
      dueDayRequired: 'Enter a due day from 1 to 31.',
      endDate: 'End date',
      financialSection: 'Financial terms',
      generatePaymentsAutomatically: 'Generate rent charges automatically',
      lifecycleAction: 'Create as active contract',
      modeTitle: {
        create: 'Create contract',
        edit: 'Edit contract',
      },
      monthlyRent: 'Monthly rent',
      monthlyRentRequired: 'Enter a valid monthly rent.',
      nextAdjustmentDate: 'Next adjustment date',
      notes: 'Notes',
      partiesSection: 'Property and residents',
      penaltyNotes: 'Penalty notes',
      primaryResident: 'Primary resident',
      primaryResidentRequired: 'Select the primary resident.',
      property: 'Property',
      propertyRequired: 'Select a property.',
      residentRequired: 'Select at least one resident and include the primary resident.',
      residents: 'Residents',
      startDate: 'Start date',
      startDateRequired: 'Enter the start date.',
      submitCreate: 'Create contract',
      submitEdit: 'Save changes',
      termsSection: 'Dates and terms',
      validationTitle: 'Review the highlighted fields',
    },
    list: {
      activeFilters: (count: number) => `${count} active filters`,
      add: 'Add contract',
      allProperties: 'All properties',
      allResidents: 'All residents',
      allStatuses: 'All statuses',
      archive: 'Archive',
      clearFilters: 'Clear filters',
      columns: {
        actions: 'Actions',
        dates: 'Dates',
        property: 'Property',
        rent: 'Rent',
        residents: 'Residents',
        status: 'Status',
      },
      edit: 'Edit',
      empty: 'No contracts found.',
      endingSoonOnly: 'Ending soon',
      error: 'Could not load contracts.',
      filters: 'Filters',
      loading: 'Loading contracts...',
      pageDescription: 'Manage lease contracts, linked residents, dates, and financial terms.',
      pageTitle: 'Contracts',
      restore: 'Restore',
      search: 'Search contracts',
      searchPlaceholder: 'Search by property, resident, date, or status',
      status: {
        active: 'Active',
        archived: 'Archived',
        cancelled: 'Cancelled',
        draft: 'Draft',
        ended: 'Ended',
        'ending-soon': 'Ending soon',
        terminated: 'Terminated',
      } satisfies Record<ContractStatus, string>,
      statusActions: {
        activate: 'Activate',
        cancel: 'Cancel',
        terminate: 'Terminate',
      },
      view: 'View details',
    },
    pagination: {
      next: 'Next',
      page: (page: number, totalPages: number) => `Page ${page} of ${totalPages}`,
      previous: 'Previous',
      range: (first: number, last: number, total: number) => `Showing ${first}-${last} of ${total}`,
    },
    terms: {
      adjustmentIndexes: {
        fixed: 'Fixed percentage',
        igpm: 'IGP-M',
        ipca: 'IPCA',
        other: 'Other',
      } satisfies Record<ContractAdjustmentIndex, string>,
      noEndDate: 'Open-ended',
      residentsCount: (count: number) => `${count} residents`,
    },
  },
  'pt-BR': {
    detail: {
      actions: {
        back: 'Voltar para contratos',
        edit: 'Editar contrato',
      },
      audit: {
        archivedAt: 'Arquivado em',
        createdAt: 'Criado em',
        updatedAt: 'Atualizado em',
      },
      documentsTitle: 'Vinculos de documentos',
      emptyRelationship: 'Este relacionamento aparecera aqui quando estiver conectado.',
      error: 'Nao foi possivel carregar os detalhes do contrato.',
      labels: {
        adjustment: 'Reajuste',
        deposit: 'Caucao',
        discount: 'Observacoes de desconto',
        dueDay: 'Dia de vencimento',
        endDate: 'Fim',
        monthlyRent: 'Aluguel mensal',
        notes: 'Observacoes',
        penalty: 'Observacoes de multa',
        primaryResident: 'Responsavel principal',
        property: 'Imovel',
        residents: 'Moradores',
        startDate: 'Inicio',
        status: 'Status',
      },
      loading: 'Carregando detalhes do contrato...',
      noNotes: 'Nenhuma observacao cadastrada.',
      pageDescription: 'Revise termos, moradores, imovel, documentos e registros relacionados.',
      relationshipTitle: 'Relacionamentos',
      summaryTitle: 'Resumo do contrato',
    },
    form: {
      adjustmentIndex: 'Indice de reajuste',
      adjustmentIntervalMonths: 'Intervalo de reajuste em meses',
      adjustmentRequired: 'Selecione um indice de reajuste.',
      cancel: 'Cancelar',
      dateRangeRequired: 'A data final nao pode ser anterior ao inicio.',
      depositAmount: 'Caucao',
      discountNotes: 'Observacoes de desconto',
      documentSection: 'Documentos',
      documentSummary: 'Vinculos do contrato assinado sao gerenciados em Documentos.',
      dueDay: 'Dia de vencimento',
      dueDayRequired: 'Informe um dia de 1 a 31.',
      endDate: 'Fim',
      financialSection: 'Termos financeiros',
      generatePaymentsAutomatically: 'Gerar cobrancas de aluguel automaticamente',
      lifecycleAction: 'Criar como contrato ativo',
      modeTitle: {
        create: 'Criar contrato',
        edit: 'Editar contrato',
      },
      monthlyRent: 'Aluguel mensal',
      monthlyRentRequired: 'Informe um aluguel mensal valido.',
      nextAdjustmentDate: 'Proximo reajuste',
      notes: 'Observacoes',
      partiesSection: 'Imovel e moradores',
      penaltyNotes: 'Observacoes de multa',
      primaryResident: 'Responsavel principal',
      primaryResidentRequired: 'Selecione o responsavel principal.',
      property: 'Imovel',
      propertyRequired: 'Selecione um imovel.',
      residentRequired: 'Selecione ao menos um morador e inclua o responsavel principal.',
      residents: 'Moradores',
      startDate: 'Inicio',
      startDateRequired: 'Informe a data de inicio.',
      submitCreate: 'Criar contrato',
      submitEdit: 'Salvar alteracoes',
      termsSection: 'Datas e termos',
      validationTitle: 'Revise os campos destacados',
    },
    list: {
      activeFilters: (count: number) => `${count} filtros ativos`,
      add: 'Adicionar contrato',
      allProperties: 'Todos os imoveis',
      allResidents: 'Todos os moradores',
      allStatuses: 'Todos os status',
      archive: 'Arquivar',
      clearFilters: 'Limpar filtros',
      columns: {
        actions: 'Acoes',
        dates: 'Datas',
        property: 'Imovel',
        rent: 'Aluguel',
        residents: 'Moradores',
        status: 'Status',
      },
      edit: 'Editar',
      empty: 'Nenhum contrato encontrado.',
      endingSoonOnly: 'A vencer',
      error: 'Nao foi possivel carregar os contratos.',
      filters: 'Filtros',
      loading: 'Carregando contratos...',
      pageDescription:
        'Gerencie contratos de aluguel, moradores vinculados, datas e termos financeiros.',
      pageTitle: 'Contratos',
      restore: 'Restaurar',
      search: 'Buscar contratos',
      searchPlaceholder: 'Busque por imovel, morador, data ou status',
      status: {
        active: 'Ativo',
        archived: 'Arquivado',
        cancelled: 'Cancelado',
        draft: 'Rascunho',
        ended: 'Encerrado',
        'ending-soon': 'A vencer',
        terminated: 'Rescindido',
      } satisfies Record<ContractStatus, string>,
      statusActions: {
        activate: 'Ativar',
        cancel: 'Cancelar',
        terminate: 'Rescindir',
      },
      view: 'Ver detalhes',
    },
    pagination: {
      next: 'Proxima',
      page: (page: number, totalPages: number) => `Pagina ${page} de ${totalPages}`,
      previous: 'Anterior',
      range: (first: number, last: number, total: number) =>
        `Exibindo ${first}-${last} de ${total}`,
    },
    terms: {
      adjustmentIndexes: {
        fixed: 'Percentual fixo',
        igpm: 'IGP-M',
        ipca: 'IPCA',
        other: 'Outro',
      } satisfies Record<ContractAdjustmentIndex, string>,
      noEndDate: 'Sem data final',
      residentsCount: (count: number) => `${count} moradores`,
    },
  },
} as const

export function getContractCopy(locale: AppLocale) {
  return contractCopies[normalizeAppLocale(locale)]
}
