import { normalizeAppLocale, type AppLocale } from '../../i18n'
import type { ResidentPortalStatus, ResidentStatus } from '../../lib/api/residents'

const residentCopies = {
  'en-US': {
    detail: {
      actions: {
        back: 'Back to residents',
        edit: 'Edit resident',
      },
      audit: {
        archivedAt: 'Archived at',
        createdAt: 'Created at',
        updatedAt: 'Updated at',
      },
      emptyRelationship: 'This relationship will appear here when connected.',
      error: 'Could not load resident details.',
      labels: {
        birthDate: 'Birth date',
        document: 'Document',
        email: 'Email',
        emergencyContact: 'Emergency contact',
        fullName: 'Full name',
        notes: 'Notes',
        phone: 'Phone',
        portalStatus: 'Portal status',
        preferredName: 'Preferred name',
        privacyFlags: 'Privacy flags',
        secondaryPhone: 'Secondary phone',
        status: 'Status',
      },
      loading: 'Loading resident details...',
      maskedValue: 'Restricted data',
      noNotes: 'No notes registered.',
      noValue: '-',
      pageDescription: 'Review resident profile, privacy, portal access, and linked records.',
      privacyNone: 'No privacy flags.',
      relationshipCount: (count: number) => `${count} linked record${count === 1 ? '' : 's'}`,
      relationships: {
        audit: {
          description: 'Audit events filtered by this resident.',
          linkTitle: 'Open resident audit',
          title: 'Audit',
        },
        contracts: {
          title: 'Contracts',
        },
        documents: {
          title: 'Documents',
        },
        occurrences: {
          title: 'Occurrences',
        },
        payments: {
          title: 'Payments',
        },
        pets: {
          title: 'Pets',
        },
        properties: {
          title: 'Properties',
        },
        timeline: {
          description: 'Operational timeline filtered by this resident.',
          linkTitle: 'Open resident timeline',
          title: 'Timeline',
        },
        vehicles: {
          title: 'Vehicles',
        },
      },
      relationshipTitle: 'Relationships',
      summaryTitle: 'Resident summary',
    },
    form: {
      birthDate: 'Birth date',
      cancel: 'Cancel',
      checkDuplicates: 'Check duplicates',
      contactRequired: 'Enter an email or phone.',
      contactSection: 'Contact',
      documentIdentifier: 'Document number',
      documentType: 'Document type',
      duplicateError: 'Could not check duplicates.',
      duplicateNoCriteria: 'Enter email, phone, or document to check.',
      duplicateNone: 'No possible duplicates found.',
      duplicateSection: 'Duplicate warnings',
      duplicateWarningTitle: 'Possible duplicate records',
      email: 'Email',
      emailInvalid: 'Enter a valid email.',
      emergencyContactName: 'Name',
      emergencyContactPhone: 'Phone',
      emergencyContactRelationship: 'Relationship',
      emergencySection: 'Emergency contact',
      fullName: 'Full name',
      fullNameRequired: 'Enter the full name.',
      identificationSection: 'Identification',
      modeTitle: {
        create: 'Create resident',
        edit: 'Edit resident',
      },
      notes: 'Notes',
      personalSection: 'Personal data',
      phone: 'Phone',
      portalSection: 'Portal access',
      portalStatus: 'Portal status',
      portalStatusRequired: 'Select a portal status.',
      preferredName: 'Preferred name',
      privacyFlags: {
        'contact-data': 'Restrict contact data',
        'emergency-contact': 'Emergency contact only',
        'identification-data': 'Restrict identification data',
        notes: 'Restrict notes',
      },
      privacySection: 'Privacy',
      secondaryPhone: 'Secondary phone',
      status: 'Status',
      statusRequired: 'Select a status.',
      submitCreate: 'Create resident',
      submitEdit: 'Save changes',
      validationTitle: 'Review the highlighted fields',
    },
    list: {
      activeFilters: (count: number) => `${count} active filters`,
      add: 'Add resident',
      allPortalAccess: 'Any portal access',
      allPortalStatuses: 'All portal statuses',
      allStatuses: 'All statuses',
      archive: 'Archive',
      clearFilters: 'Clear filters',
      columns: {
        actions: 'Actions',
        contact: 'Contact',
        document: 'Document',
        portalStatus: 'Portal status',
        resident: 'Resident',
        status: 'Status',
      },
      edit: 'Edit',
      empty: 'No residents found.',
      error: 'Could not load residents.',
      filters: 'Filters',
      includeArchived: 'Include archived',
      loading: 'Loading residents...',
      masked: 'Restricted',
      maskedContact: 'Restricted contact',
      noDocument: '-',
      pageDescription: 'Manage resident profiles, contacts, privacy, and portal access.',
      pageTitle: 'Residents',
      portalAccess: 'Portal access',
      portalAccessNo: 'Without access',
      portalAccessYes: 'With access',
      portalStatus: {
        active: 'Active',
        disabled: 'Disabled',
        invited: 'Invited',
        'not-invited': 'Not invited',
      } satisfies Record<ResidentPortalStatus, string>,
      restore: 'Restore',
      search: 'Search residents',
      searchPlaceholder: 'Search by name, email, phone, or document',
      status: {
        active: 'Active',
        archived: 'Archived',
        inactive: 'Inactive',
      } satisfies Record<ResidentStatus, string>,
      view: 'View details',
    },
    pagination: {
      next: 'Next',
      page: (page: number, totalPages: number) => `Page ${page} of ${totalPages}`,
      previous: 'Previous',
      range: (first: number, last: number, total: number) => `Showing ${first}-${last} of ${total}`,
    },
  },
  'pt-BR': {
    detail: {
      actions: {
        back: 'Voltar para moradores',
        edit: 'Editar morador',
      },
      audit: {
        archivedAt: 'Arquivado em',
        createdAt: 'Criado em',
        updatedAt: 'Atualizado em',
      },
      emptyRelationship: 'Este relacionamento aparecera aqui quando estiver conectado.',
      error: 'Nao foi possivel carregar os detalhes do morador.',
      labels: {
        birthDate: 'Data de nascimento',
        document: 'Documento',
        email: 'E-mail',
        emergencyContact: 'Contato de emergencia',
        fullName: 'Nome completo',
        notes: 'Observacoes',
        phone: 'Telefone',
        portalStatus: 'Status do portal',
        preferredName: 'Nome social',
        privacyFlags: 'Privacidade',
        secondaryPhone: 'Telefone secundario',
        status: 'Status',
      },
      loading: 'Carregando detalhes do morador...',
      maskedValue: 'Dados restritos',
      noNotes: 'Nenhuma observacao cadastrada.',
      noValue: '-',
      pageDescription: 'Revise perfil, privacidade, acesso ao portal e registros vinculados.',
      privacyNone: 'Nenhuma restricao de privacidade.',
      relationshipCount: (count: number) => `${count} vinculo${count === 1 ? '' : 's'}`,
      relationships: {
        audit: {
          description: 'Eventos de auditoria filtrados por este morador.',
          linkTitle: 'Abrir auditoria do morador',
          title: 'Auditoria',
        },
        contracts: {
          title: 'Contratos',
        },
        documents: {
          title: 'Documentos',
        },
        occurrences: {
          title: 'Ocorrencias',
        },
        payments: {
          title: 'Pagamentos',
        },
        pets: {
          title: 'Pets',
        },
        properties: {
          title: 'Imoveis',
        },
        timeline: {
          description: 'Timeline operacional filtrada por este morador.',
          linkTitle: 'Abrir timeline do morador',
          title: 'Timeline',
        },
        vehicles: {
          title: 'Veiculos',
        },
      },
      relationshipTitle: 'Relacionamentos',
      summaryTitle: 'Resumo do morador',
    },
    form: {
      birthDate: 'Data de nascimento',
      cancel: 'Cancelar',
      checkDuplicates: 'Verificar duplicidades',
      contactRequired: 'Informe e-mail ou telefone.',
      contactSection: 'Contato',
      documentIdentifier: 'Numero do documento',
      documentType: 'Tipo do documento',
      duplicateError: 'Nao foi possivel verificar duplicidades.',
      duplicateNoCriteria: 'Informe e-mail, telefone ou documento para verificar.',
      duplicateNone: 'Nenhuma duplicidade encontrada.',
      duplicateSection: 'Alertas de duplicidade',
      duplicateWarningTitle: 'Possiveis registros duplicados',
      email: 'E-mail',
      emailInvalid: 'Informe um e-mail valido.',
      emergencyContactName: 'Nome',
      emergencyContactPhone: 'Telefone',
      emergencyContactRelationship: 'Parentesco',
      emergencySection: 'Contato de emergencia',
      fullName: 'Nome completo',
      fullNameRequired: 'Informe o nome completo.',
      identificationSection: 'Identificacao',
      modeTitle: {
        create: 'Criar morador',
        edit: 'Editar morador',
      },
      notes: 'Observacoes',
      personalSection: 'Dados pessoais',
      phone: 'Telefone',
      portalSection: 'Acesso ao portal',
      portalStatus: 'Status do portal',
      portalStatusRequired: 'Selecione um status do portal.',
      preferredName: 'Nome social',
      privacyFlags: {
        'contact-data': 'Restringir dados de contato',
        'emergency-contact': 'Contato apenas emergencial',
        'identification-data': 'Restringir identificacao',
        notes: 'Restringir observacoes',
      },
      privacySection: 'Privacidade',
      secondaryPhone: 'Telefone secundario',
      status: 'Status',
      statusRequired: 'Selecione um status.',
      submitCreate: 'Criar morador',
      submitEdit: 'Salvar alteracoes',
      validationTitle: 'Revise os campos destacados',
    },
    list: {
      activeFilters: (count: number) => `${count} filtros ativos`,
      add: 'Adicionar morador',
      allPortalAccess: 'Qualquer acesso',
      allPortalStatuses: 'Todos os status do portal',
      allStatuses: 'Todos os status',
      archive: 'Arquivar',
      clearFilters: 'Limpar filtros',
      columns: {
        actions: 'Acoes',
        contact: 'Contato',
        document: 'Documento',
        portalStatus: 'Status do portal',
        resident: 'Morador',
        status: 'Status',
      },
      edit: 'Editar',
      empty: 'Nenhum morador encontrado.',
      error: 'Nao foi possivel carregar os moradores.',
      filters: 'Filtros',
      includeArchived: 'Incluir arquivados',
      loading: 'Carregando moradores...',
      masked: 'Restrito',
      maskedContact: 'Contato restrito',
      noDocument: '-',
      pageDescription: 'Gerencie perfis, contatos, privacidade e acesso ao portal dos moradores.',
      pageTitle: 'Moradores',
      portalAccess: 'Acesso ao portal',
      portalAccessNo: 'Sem acesso',
      portalAccessYes: 'Com acesso',
      portalStatus: {
        active: 'Ativo',
        disabled: 'Desabilitado',
        invited: 'Convidado',
        'not-invited': 'Nao convidado',
      } satisfies Record<ResidentPortalStatus, string>,
      restore: 'Restaurar',
      search: 'Buscar moradores',
      searchPlaceholder: 'Busque por nome, e-mail, telefone ou documento',
      status: {
        active: 'Ativo',
        archived: 'Arquivado',
        inactive: 'Inativo',
      } satisfies Record<ResidentStatus, string>,
      view: 'Ver detalhes',
    },
    pagination: {
      next: 'Proxima',
      page: (page: number, totalPages: number) => `Pagina ${page} de ${totalPages}`,
      previous: 'Anterior',
      range: (first: number, last: number, total: number) =>
        `Exibindo ${first}-${last} de ${total}`,
    },
  },
} as const

export function getResidentCopy(locale: AppLocale) {
  return residentCopies[normalizeAppLocale(locale)]
}
