import { normalizeAppLocale, type AppLocale } from '../../i18n'

const notificationCopies = {
  'en-US': {
    list: {
      activeFilters: (count: number) => `${count} active filters`,
      allCategories: 'All categories',
      allChannels: 'All channels',
      allReadStates: 'All read states',
      archive: 'Archive',
      categories: 'Category',
      channels: 'Channel',
      clearFilters: 'Clear filters',
      columns: {
        actions: 'Actions',
        category: 'Category',
        channel: 'Channel',
        notification: 'Notification',
        occurredAt: 'Date',
        readState: 'State',
      },
      deepLink: 'Open source',
      empty: 'No notifications found.',
      error: 'Could not load notifications.',
      filters: 'Filters',
      includeArchived: 'Archived',
      includeArchivedNo: 'Active only',
      includeArchivedYes: 'Include archived',
      loading: 'Loading notifications...',
      markAllRead: 'Mark all read',
      markRead: 'Mark read',
      pageDescription: 'Review event-triggered messages, unread state, and source links.',
      pageTitle: 'Notifications',
      read: 'Read',
      readState: 'Read state',
      search: 'Search notifications',
      searchPlaceholder: 'Search by message, source, or category',
      unread: 'Unread',
      unreadCount: (count: number) => `${count} unread`,
    },
    pagination: {
      next: 'Next',
      page: (page: number, totalPages: number) => `Page ${page} of ${totalPages}`,
      previous: 'Previous',
      range: (first: number, last: number, total: number) => `Showing ${first}-${last} of ${total}`,
    },
    preferences: {
      cancel: 'Cancel',
      open: 'Preferences',
      save: 'Save preferences',
      title: 'Notification preferences',
    },
  },
  'pt-BR': {
    list: {
      activeFilters: (count: number) => `${count} filtros ativos`,
      allCategories: 'Todas as categorias',
      allChannels: 'Todos os canais',
      allReadStates: 'Todos os estados',
      archive: 'Arquivar',
      categories: 'Categoria',
      channels: 'Canal',
      clearFilters: 'Limpar filtros',
      columns: {
        actions: 'Acoes',
        category: 'Categoria',
        channel: 'Canal',
        notification: 'Notificacao',
        occurredAt: 'Data',
        readState: 'Estado',
      },
      deepLink: 'Abrir origem',
      empty: 'Nenhuma notificacao encontrada.',
      error: 'Nao foi possivel carregar as notificacoes.',
      filters: 'Filtros',
      includeArchived: 'Arquivadas',
      includeArchivedNo: 'Somente ativas',
      includeArchivedYes: 'Incluir arquivadas',
      loading: 'Carregando notificacoes...',
      markAllRead: 'Marcar todas como lidas',
      markRead: 'Marcar como lida',
      pageDescription: 'Revise mensagens geradas por eventos, estado de leitura e links de origem.',
      pageTitle: 'Notificacoes',
      read: 'Lidas',
      readState: 'Estado de leitura',
      search: 'Buscar notificacoes',
      searchPlaceholder: 'Busque por mensagem, origem ou categoria',
      unread: 'Nao lidas',
      unreadCount: (count: number) => `${count} nao lidas`,
    },
    pagination: {
      next: 'Proxima',
      page: (page: number, totalPages: number) => `Pagina ${page} de ${totalPages}`,
      previous: 'Anterior',
      range: (first: number, last: number, total: number) =>
        `Exibindo ${first}-${last} de ${total}`,
    },
    preferences: {
      cancel: 'Cancelar',
      open: 'Preferencias',
      save: 'Salvar preferencias',
      title: 'Preferencias de notificacao',
    },
  },
} as const

export function getNotificationCopy(locale: AppLocale) {
  return notificationCopies[normalizeAppLocale(locale)]
}
