import type { AppLocale } from '../../i18n'

const en = {
  actions: {
    close: 'Close',
    createOccurrence: 'Create occurrence',
    generateInstructions: 'Generate instructions',
    retry: 'Retry',
    submit: 'Submit',
    uploadDocument: 'Upload document',
  },
  documents: {
    category: 'Category',
    description: 'Description',
    file: 'File',
    title: 'Documents',
    uploadDisabled: 'Document uploads are disabled by the organization.',
    versionNotes: 'Version notes',
  },
  empty: {
    contracts: 'No visible contracts.',
    documents: 'No visible documents.',
    inspections: 'No visible inspections.',
    notifications: 'No notifications.',
    occurrences: 'No occurrences.',
    payments: 'No visible payments.',
    property: 'No linked property.',
  },
  fields: {
    amount: 'Amount',
    balance: 'Balance',
    city: 'City',
    completed: 'Completed',
    contact: 'Contact',
    contract: 'Contract',
    dueDate: 'Due date',
    dueDay: 'Due day',
    email: 'Email',
    endDate: 'End date',
    fileName: 'File',
    fullName: 'Full name',
    method: 'Method',
    monthlyRent: 'Monthly rent',
    neighborhood: 'Neighborhood',
    paid: 'Paid',
    phone: 'Phone',
    priority: 'Priority',
    progress: 'Progress',
    property: 'Property',
    provider: 'Provider',
    scheduledAt: 'Scheduled at',
    size: 'Size',
    startDate: 'Start date',
    status: 'Status',
    title: 'Title',
    type: 'Type',
    uploadedAt: 'Uploaded at',
  },
  forms: {
    category: 'Category',
    description: 'Description',
    file: 'File',
    priority: 'Priority',
    property: 'Property',
    title: 'Title',
    type: 'Type',
  },
  loading: 'Loading resident portal',
  nav: {
    contracts: 'Contracts',
    documents: 'Documents',
    inspections: 'Inspections',
    notifications: 'Notifications',
    occurrences: 'Occurrences',
    overview: 'Overview',
    payments: 'Payments',
    profile: 'Profile',
    property: 'Property',
  },
  occurrences: {
    createDisabled: 'Occurrence creation is disabled by the organization.',
    description: 'Describe what happened',
    priority: 'Priority',
    title: 'Occurrences',
    type: 'Type',
  },
  overview: {
    subtitle:
      'A resident-only view of your linked property, contracts, payments, documents, and requests.',
    title: 'Resident portal',
  },
  payments: {
    boleto: 'Boleto',
    instructions: 'Payment instructions',
    payPal: 'PayPal',
    pix: 'Pix',
    provider: 'Provider',
    title: 'Payments',
  },
  shell: {
    account: 'Resident account',
    brandSubtitle: 'Resident portal',
    localeToggle: 'Change language',
    menu: 'Resident navigation',
    notifications: 'Notifications',
    signOut: 'Sign out',
    themeToggle: 'Toggle theme',
  },
  states: {
    error: 'Could not load the resident portal.',
    saved: 'Saved.',
  },
}

const pt: typeof en = {
  actions: {
    close: 'Fechar',
    createOccurrence: 'Criar ocorrencia',
    generateInstructions: 'Gerar instrucoes',
    retry: 'Tentar novamente',
    submit: 'Enviar',
    uploadDocument: 'Enviar documento',
  },
  documents: {
    category: 'Categoria',
    description: 'Descricao',
    file: 'Arquivo',
    title: 'Documentos',
    uploadDisabled: 'Envio de documentos esta desativado pela organizacao.',
    versionNotes: 'Notas da versao',
  },
  empty: {
    contracts: 'Nenhum contrato visivel.',
    documents: 'Nenhum documento visivel.',
    inspections: 'Nenhuma vistoria visivel.',
    notifications: 'Nenhuma notificacao.',
    occurrences: 'Nenhuma ocorrencia.',
    payments: 'Nenhum pagamento visivel.',
    property: 'Nenhum imovel vinculado.',
  },
  fields: {
    amount: 'Valor',
    balance: 'Saldo',
    city: 'Cidade',
    completed: 'Concluido',
    contact: 'Contato',
    contract: 'Contrato',
    dueDate: 'Vencimento',
    dueDay: 'Dia de vencimento',
    email: 'Email',
    endDate: 'Fim',
    fileName: 'Arquivo',
    fullName: 'Nome completo',
    method: 'Metodo',
    monthlyRent: 'Aluguel mensal',
    neighborhood: 'Bairro',
    paid: 'Pago',
    phone: 'Telefone',
    priority: 'Prioridade',
    progress: 'Progresso',
    property: 'Imovel',
    provider: 'Provedor',
    scheduledAt: 'Agendada para',
    size: 'Tamanho',
    startDate: 'Inicio',
    status: 'Status',
    title: 'Titulo',
    type: 'Tipo',
    uploadedAt: 'Enviado em',
  },
  forms: {
    category: 'Categoria',
    description: 'Descricao',
    file: 'Arquivo',
    priority: 'Prioridade',
    property: 'Imovel',
    title: 'Titulo',
    type: 'Tipo',
  },
  loading: 'Carregando portal do morador',
  nav: {
    contracts: 'Contratos',
    documents: 'Documentos',
    inspections: 'Vistorias',
    notifications: 'Notificacoes',
    occurrences: 'Ocorrencias',
    overview: 'Resumo',
    payments: 'Pagamentos',
    profile: 'Perfil',
    property: 'Imovel',
  },
  occurrences: {
    createDisabled: 'Criacao de ocorrencias esta desativada pela organizacao.',
    description: 'Descreva o que aconteceu',
    priority: 'Prioridade',
    title: 'Ocorrencias',
    type: 'Tipo',
  },
  overview: {
    subtitle:
      'Uma visao exclusiva do morador para imovel, contratos, pagamentos, documentos e solicitacoes.',
    title: 'Portal do morador',
  },
  payments: {
    boleto: 'Boleto',
    instructions: 'Instrucoes de pagamento',
    payPal: 'PayPal',
    pix: 'Pix',
    provider: 'Provedor',
    title: 'Pagamentos',
  },
  shell: {
    account: 'Conta do morador',
    brandSubtitle: 'Portal do morador',
    localeToggle: 'Alterar idioma',
    menu: 'Navegacao do morador',
    notifications: 'Notificacoes',
    signOut: 'Sair',
    themeToggle: 'Alternar tema',
  },
  states: {
    error: 'Nao foi possivel carregar o portal do morador.',
    saved: 'Salvo.',
  },
}

export function getResidentPortalCopy(locale: AppLocale) {
  return locale === 'en-US' ? en : pt
}
