import { normalizeAppLocale, type AppLocale } from '../../i18n'
import type { PropertyStatus, PropertyType } from '../../lib/api/properties'

const propertyCopies = {
  'en-US': {
    detail: {
      actions: {
        back: 'Back to properties',
        edit: 'Edit property',
      },
      audit: {
        createdAt: 'Created at',
        updatedAt: 'Updated at',
      },
      emptyRelationship: 'This relationship will appear here when connected.',
      error: 'Could not load property details.',
      labels: {
        address: 'Address',
        garage: 'Garage',
        notes: 'Notes',
        rent: 'Suggested rent',
        status: 'Status',
        type: 'Type',
      },
      loading: 'Loading property details...',
      noNotes: 'No notes registered.',
      pageDescription: 'Review property data and connected operational records.',
      relationships: {
        audit: {
          description: 'Audit events filtered by this property.',
          linkTitle: 'Open property audit',
          title: 'Audit',
        },
        contracts: {
          title: 'Contracts',
        },
        documents: {
          title: 'Documents',
        },
        inspections: {
          title: 'Inspections',
        },
        occurrences: {
          title: 'Occurrences',
        },
        payments: {
          title: 'Payments',
        },
        pets: {
          title: 'Pets',
        },
        residents: {
          title: 'Residents',
        },
        timeline: {
          description: 'Operational timeline filtered by this property.',
          linkTitle: 'Open property timeline',
          title: 'Timeline',
        },
        utilities: {
          title: 'Utilities',
        },
        vehicles: {
          title: 'Vehicles',
        },
      },
      relationshipTitle: 'Relationships',
      summaryTitle: 'Property summary',
    },
    form: {
      addressSection: 'Address',
      cancel: 'Cancel',
      city: 'City',
      cityRequired: 'Enter the city.',
      complement: 'Complement',
      country: 'Country',
      garageSection: 'Garage',
      garageSpaces: 'Garage spaces',
      garageSpacesRequired: 'Enter the number of garage spaces.',
      hasGarage: 'Has garage',
      modeTitle: {
        create: 'Create property',
        edit: 'Edit property',
      },
      name: 'Property',
      nameRequired: 'Enter the property name.',
      neighborhood: 'Neighborhood',
      neighborhoodRequired: 'Enter the neighborhood.',
      notes: 'Notes',
      number: 'Number',
      postalCode: 'Postal code',
      rentSection: 'Rent and status',
      state: 'State',
      stateRequired: 'Enter the state.',
      status: 'Status',
      statusRequired: 'Select a status.',
      street: 'Street',
      streetRequired: 'Enter the street.',
      submitCreate: 'Create property',
      submitEdit: 'Save changes',
      suggestedRent: 'Suggested rent',
      suggestedRentRequired: 'Enter a valid suggested rent.',
      type: 'Type',
      validationTitle: 'Review the highlighted fields',
    },
    list: {
      activeFilters: (count: number) => `${count} active filters`,
      add: 'Add property',
      allGarage: 'Any garage',
      allStatuses: 'All statuses',
      allTypes: 'All types',
      archive: 'Archive',
      archivedGarage: 'Archived',
      clearFilters: 'Clear filters',
      columns: {
        actions: 'Actions',
        garage: 'Garage',
        location: 'Location',
        property: 'Property',
        status: 'Status',
        suggestedRent: 'Suggested rent',
      },
      edit: 'Edit',
      empty: 'No properties found.',
      error: 'Could not load properties.',
      filters: 'Filters',
      garageNo: 'No garage',
      garageSpaces: (count: number) => `${count} spaces`,
      garageYes: 'With garage',
      hasGarage: 'Garage',
      includeArchived: 'Include archived',
      loading: 'Loading properties...',
      markAvailable: 'Mark available',
      markMaintenance: 'Mark maintenance',
      maxRent: 'Max rent',
      minRent: 'Min rent',
      pageDescription: 'Manage the property catalog, availability, rent, garage data, and links.',
      pageTitle: 'Properties',
      restore: 'Restore',
      search: 'Search properties',
      searchPlaceholder: 'Search by property or address',
      status: {
        archived: 'Archived',
        available: 'Available',
        inactive: 'Inactive',
        maintenance: 'Maintenance',
        rented: 'Rented',
        reserved: 'Reserved',
      } satisfies Record<PropertyStatus, string>,
      type: 'Type',
      types: {
        apartment: 'Apartment',
        'commercial-room': 'Commercial room',
        house: 'House',
        land: 'Land',
        other: 'Other',
      } satisfies Record<PropertyType, string>,
      view: 'View details',
    },
    pagination: {
      next: 'Next',
      page: (page: number, totalPages: number) => `Page ${page} of ${totalPages}`,
      previous: 'Previous',
      range: (first: number, last: number, total: number) => `Showing ${first}-${last} of ${total}`,
    },
  },
  'pt-BR': {
    detail: {
      actions: {
        back: 'Voltar para imoveis',
        edit: 'Editar imovel',
      },
      audit: {
        createdAt: 'Criado em',
        updatedAt: 'Atualizado em',
      },
      emptyRelationship: 'Este relacionamento aparecera aqui quando estiver conectado.',
      error: 'Nao foi possivel carregar os detalhes do imovel.',
      labels: {
        address: 'Endereco',
        garage: 'Garagem',
        notes: 'Observacoes',
        rent: 'Aluguel sugerido',
        status: 'Status',
        type: 'Tipo',
      },
      loading: 'Carregando detalhes do imovel...',
      noNotes: 'Nenhuma observacao cadastrada.',
      pageDescription: 'Revise dados do imovel e registros operacionais conectados.',
      relationships: {
        audit: {
          description: 'Eventos de auditoria filtrados por este imovel.',
          linkTitle: 'Abrir auditoria do imovel',
          title: 'Auditoria',
        },
        contracts: {
          title: 'Contratos',
        },
        documents: {
          title: 'Documentos',
        },
        inspections: {
          title: 'Vistorias',
        },
        occurrences: {
          title: 'Ocorrencias',
        },
        payments: {
          title: 'Pagamentos',
        },
        pets: {
          title: 'Pets',
        },
        residents: {
          title: 'Moradores',
        },
        timeline: {
          description: 'Timeline operacional filtrada por este imovel.',
          linkTitle: 'Abrir timeline do imovel',
          title: 'Timeline',
        },
        utilities: {
          title: 'Contas de consumo',
        },
        vehicles: {
          title: 'Veiculos',
        },
      },
      relationshipTitle: 'Relacionamentos',
      summaryTitle: 'Resumo do imovel',
    },
    form: {
      addressSection: 'Endereco',
      cancel: 'Cancelar',
      city: 'Cidade',
      cityRequired: 'Informe a cidade.',
      complement: 'Complemento',
      country: 'Pais',
      garageSection: 'Garagem',
      garageSpaces: 'Vagas de garagem',
      garageSpacesRequired: 'Informe a quantidade de vagas.',
      hasGarage: 'Possui garagem',
      modeTitle: {
        create: 'Criar imovel',
        edit: 'Editar imovel',
      },
      name: 'Imovel',
      nameRequired: 'Informe o imovel.',
      neighborhood: 'Bairro',
      neighborhoodRequired: 'Informe o bairro.',
      notes: 'Observacoes',
      number: 'Numero',
      postalCode: 'CEP',
      rentSection: 'Aluguel e status',
      state: 'UF',
      stateRequired: 'Informe a UF.',
      status: 'Status',
      statusRequired: 'Selecione um status.',
      street: 'Logradouro',
      streetRequired: 'Informe o logradouro.',
      submitCreate: 'Criar imovel',
      submitEdit: 'Salvar alteracoes',
      suggestedRent: 'Aluguel sugerido',
      suggestedRentRequired: 'Informe um aluguel sugerido valido.',
      type: 'Tipo',
      validationTitle: 'Revise os campos destacados',
    },
    list: {
      activeFilters: (count: number) => `${count} filtros ativos`,
      add: 'Adicionar imovel',
      allGarage: 'Qualquer garagem',
      allStatuses: 'Todos os status',
      allTypes: 'Todos os tipos',
      archive: 'Arquivar',
      archivedGarage: 'Arquivado',
      clearFilters: 'Limpar filtros',
      columns: {
        actions: 'Acoes',
        garage: 'Garagem',
        location: 'Localizacao',
        property: 'Imovel',
        status: 'Status',
        suggestedRent: 'Aluguel sugerido',
      },
      edit: 'Editar',
      empty: 'Nenhum imovel encontrado.',
      error: 'Nao foi possivel carregar os imoveis.',
      filters: 'Filtros',
      garageNo: 'Sem garagem',
      garageSpaces: (count: number) => `${count} vagas`,
      garageYes: 'Com garagem',
      hasGarage: 'Garagem',
      includeArchived: 'Incluir arquivados',
      loading: 'Carregando imoveis...',
      markAvailable: 'Marcar disponivel',
      markMaintenance: 'Marcar manutencao',
      maxRent: 'Aluguel maximo',
      minRent: 'Aluguel minimo',
      pageDescription:
        'Gerencie o catalogo de imoveis, disponibilidade, aluguel, garagem e vinculos.',
      pageTitle: 'Imoveis',
      restore: 'Restaurar',
      search: 'Buscar imoveis',
      searchPlaceholder: 'Busque por imovel ou endereco',
      status: {
        archived: 'Arquivado',
        available: 'Disponivel',
        inactive: 'Inativo',
        maintenance: 'Manutencao',
        rented: 'Alugado',
        reserved: 'Reservado',
      } satisfies Record<PropertyStatus, string>,
      type: 'Tipo',
      types: {
        apartment: 'Apartamento',
        'commercial-room': 'Sala comercial',
        house: 'Casa',
        land: 'Terreno',
        other: 'Outro',
      } satisfies Record<PropertyType, string>,
      view: 'Ver detalhes',
    },
    pagination: {
      next: 'Proxima',
      page: (page: number, totalPages: number) => `Pagina ${page} de ${totalPages}`,
      previous: 'Anterior',
      range: (first: number, last: number, total: number) =>
        `Exibindo ${first}-${last} de ${total}`,
    },
  },
} as const

export function getPropertyCopy(locale: AppLocale) {
  return propertyCopies[normalizeAppLocale(locale)]
}
