import { normalizeAppLocale, type AppLocale } from '../../i18n'
import type {
  OccurrencePriority,
  OccurrenceStatus,
  OccurrenceType,
} from '../../lib/api/occurrences'

const occurrenceCopies = {
  'en-US': {
    detail: {
      actions: {
        archive: 'Archive',
        back: 'Back to occurrences',
        cancel: 'Cancel occurrence',
        edit: 'Edit occurrence',
        restore: 'Restore',
        resolve: 'Resolve',
      },
      attachment: {
        add: 'Attach document',
        documentId: 'Document ID',
        empty: 'No documents attached.',
        label: 'Label',
        title: 'Attachments',
      },
      audit: {
        archivedAt: 'Archived at',
        createdAt: 'Created at',
        updatedAt: 'Updated at',
      },
      comments: {
        add: 'Add comment',
        body: 'Comment',
        empty: 'No comments yet.',
        internal: 'Internal comment',
        title: 'Comments',
      },
      emptyRelationship: 'This relationship will appear here when connected.',
      error: 'Could not load occurrence details.',
      history: {
        assignment: 'Assignment history',
        priority: 'Priority history',
        status: 'Status history',
      },
      labels: {
        assignedUser: 'Assignee',
        contract: 'Contract',
        description: 'Description',
        dueDate: 'Due date',
        priority: 'Priority',
        property: 'Property',
        resident: 'Resident',
        resolution: 'Resolution notes',
        status: 'Status',
        title: 'Title',
        type: 'Type',
      },
      loading: 'Loading occurrence details...',
      noNotes: 'No notes registered.',
      pageDescription: 'Coordinate assignments, comments, attachments, status, and resolution.',
      relationshipTitle: 'Relationships',
      relationships: {
        audit: 'Audit',
        timeline: 'Timeline',
      },
      workflow: {
        assign: 'Assign',
        assignee: 'Assignee',
        cancelOccurrence: 'Cancel occurrence',
        cancelNotes: 'Cancellation notes',
        changePriority: 'Change priority',
        changeStatus: 'Change status',
        notes: 'Notes',
        resolutionNotes: 'Resolution notes',
        title: 'Workflow',
      },
    },
    form: {
      assigneeSection: 'Assignment',
      assignedUserId: 'Assignee',
      cancel: 'Cancel',
      contractId: 'Contract',
      description: 'Description',
      descriptionRequired: 'Enter the occurrence description.',
      dueDate: 'Due date',
      identifiersSection: 'Linked records',
      metadataSection: 'Occurrence data',
      modeTitle: {
        create: 'Create occurrence',
        edit: 'Edit occurrence',
      },
      priority: 'Priority',
      priorityRequired: 'Select the priority.',
      propertyId: 'Property',
      propertyRequired: 'Link a property, resident, or contract.',
      residentId: 'Resident',
      submitCreate: 'Create occurrence',
      submitEdit: 'Save changes',
      title: 'Title',
      titleRequired: 'Enter the occurrence title.',
      type: 'Type',
      typeRequired: 'Select the occurrence type.',
      validationTitle: 'Review the highlighted fields',
    },
    list: {
      activeFilters: (count: number) => `${count} active filters`,
      add: 'New occurrence',
      allAssignees: 'All assignees',
      allPriorities: 'All',
      allStatuses: 'All',
      allTypes: 'All',
      archive: 'Archive',
      clearFilters: 'Clear filters',
      columns: {
        actions: 'Actions',
        assignee: 'Assignee',
        dueDate: 'Due date',
        priority: 'Priority',
        property: 'Property',
        status: 'Status',
        title: 'Occurrence',
        type: 'Type',
      },
      dateFrom: 'From date',
      dateTo: 'To date',
      edit: 'Edit',
      empty: 'No occurrences found.',
      error: 'Could not load occurrences.',
      filters: 'Filters',
      includeArchived: 'Include archived',
      loading: 'Loading occurrences...',
      pageDescription:
        'Track operational issues, complaints, maintenance, assignments, and resolution.',
      pageTitle: 'Occurrences',
      contractId: 'Contract ID',
      propertyId: 'Property ID',
      residentId: 'Resident ID',
      restore: 'Restore',
      search: 'Search occurrences',
      searchPlaceholder: 'Search by title, description, property, resident, assignee, or status',
      status: {
        archived: 'Archived',
        assigned: 'Assigned',
        cancelled: 'Cancelled',
        'in-progress': 'In progress',
        open: 'Open',
        resolved: 'Resolved',
        waiting: 'Waiting',
      } satisfies Record<OccurrenceStatus, string>,
      unresolvedOnly: 'Unresolved only',
      view: 'View details',
    },
    pagination: {
      next: 'Next',
      page: (page: number, totalPages: number) => `Page ${page} of ${totalPages}`,
      previous: 'Previous',
      range: (first: number, last: number, total: number) => `Showing ${first}-${last} of ${total}`,
    },
    terms: {
      none: 'Not informed',
      priorities: {
        high: 'High',
        low: 'Low',
        medium: 'Medium',
        urgent: 'Urgent',
      } satisfies Record<OccurrencePriority, string>,
      types: {
        complaint: 'Complaint',
        incident: 'Incident',
        maintenance: 'Maintenance',
        noise: 'Noise',
        other: 'Other',
        request: 'Request',
        security: 'Security',
      } satisfies Record<OccurrenceType, string>,
    },
  },
  'pt-BR': {
    detail: {
      actions: {
        archive: 'Arquivar',
        back: 'Voltar para ocorrencias',
        cancel: 'Cancelar ocorrencia',
        edit: 'Editar ocorrencia',
        restore: 'Restaurar',
        resolve: 'Resolver',
      },
      attachment: {
        add: 'Anexar documento',
        documentId: 'ID do documento',
        empty: 'Nenhum documento anexado.',
        label: 'Rotulo',
        title: 'Anexos',
      },
      audit: {
        archivedAt: 'Arquivado em',
        createdAt: 'Criado em',
        updatedAt: 'Atualizado em',
      },
      comments: {
        add: 'Adicionar comentario',
        body: 'Comentario',
        empty: 'Nenhum comentario ainda.',
        internal: 'Comentario interno',
        title: 'Comentarios',
      },
      emptyRelationship: 'Este relacionamento aparecera aqui quando estiver conectado.',
      error: 'Nao foi possivel carregar os detalhes da ocorrencia.',
      history: {
        assignment: 'Historico de atribuicao',
        priority: 'Historico de prioridade',
        status: 'Historico de status',
      },
      labels: {
        assignedUser: 'Responsavel',
        contract: 'Contrato',
        description: 'Descricao',
        dueDate: 'Prazo',
        priority: 'Prioridade',
        property: 'Imovel',
        resident: 'Morador',
        resolution: 'Notas da resolucao',
        status: 'Status',
        title: 'Titulo',
        type: 'Tipo',
      },
      loading: 'Carregando detalhes da ocorrencia...',
      noNotes: 'Nenhuma observacao cadastrada.',
      pageDescription: 'Coordene responsaveis, comentarios, anexos, status e resolucao.',
      relationshipTitle: 'Relacionamentos',
      relationships: {
        audit: 'Auditoria',
        timeline: 'Timeline',
      },
      workflow: {
        assign: 'Atribuir',
        assignee: 'Responsavel',
        cancelOccurrence: 'Cancelar ocorrencia',
        cancelNotes: 'Notas de cancelamento',
        changePriority: 'Alterar prioridade',
        changeStatus: 'Alterar status',
        notes: 'Notas',
        resolutionNotes: 'Notas da resolucao',
        title: 'Workflow',
      },
    },
    form: {
      assigneeSection: 'Atribuicao',
      assignedUserId: 'Responsavel',
      cancel: 'Cancelar',
      contractId: 'Contrato',
      description: 'Descricao',
      descriptionRequired: 'Informe a descricao da ocorrencia.',
      dueDate: 'Prazo',
      identifiersSection: 'Registros vinculados',
      metadataSection: 'Dados da ocorrencia',
      modeTitle: {
        create: 'Criar ocorrencia',
        edit: 'Editar ocorrencia',
      },
      priority: 'Prioridade',
      priorityRequired: 'Selecione a prioridade.',
      propertyId: 'Imovel',
      propertyRequired: 'Vincule um imovel, morador ou contrato.',
      residentId: 'Morador',
      submitCreate: 'Criar ocorrencia',
      submitEdit: 'Salvar alteracoes',
      title: 'Titulo',
      titleRequired: 'Informe o titulo da ocorrencia.',
      type: 'Tipo',
      typeRequired: 'Selecione o tipo da ocorrencia.',
      validationTitle: 'Revise os campos destacados',
    },
    list: {
      activeFilters: (count: number) => `${count} filtros ativos`,
      add: 'Nova ocorrencia',
      allAssignees: 'Todos os responsaveis',
      allPriorities: 'Todas',
      allStatuses: 'Todos',
      allTypes: 'Todos',
      archive: 'Arquivar',
      clearFilters: 'Limpar filtros',
      columns: {
        actions: 'Acoes',
        assignee: 'Responsavel',
        dueDate: 'Prazo',
        priority: 'Prioridade',
        property: 'Imovel',
        status: 'Status',
        title: 'Ocorrencia',
        type: 'Tipo',
      },
      dateFrom: 'Data inicial',
      dateTo: 'Data final',
      edit: 'Editar',
      empty: 'Nenhuma ocorrencia encontrada.',
      error: 'Nao foi possivel carregar as ocorrencias.',
      filters: 'Filtros',
      includeArchived: 'Incluir arquivadas',
      loading: 'Carregando ocorrencias...',
      pageDescription:
        'Acompanhe problemas operacionais, reclamacoes, manutencao, atribuicoes e resolucao.',
      pageTitle: 'Ocorrencias',
      contractId: 'ID do contrato',
      propertyId: 'ID do imovel',
      residentId: 'ID do morador',
      restore: 'Restaurar',
      search: 'Buscar ocorrencias',
      searchPlaceholder: 'Busque por titulo, descricao, imovel, morador, responsavel ou status',
      status: {
        archived: 'Arquivada',
        assigned: 'Atribuida',
        cancelled: 'Cancelada',
        'in-progress': 'Em andamento',
        open: 'Aberta',
        resolved: 'Resolvida',
        waiting: 'Aguardando',
      } satisfies Record<OccurrenceStatus, string>,
      unresolvedOnly: 'Somente nao resolvidas',
      view: 'Ver detalhes',
    },
    pagination: {
      next: 'Proxima',
      page: (page: number, totalPages: number) => `Pagina ${page} de ${totalPages}`,
      previous: 'Anterior',
      range: (first: number, last: number, total: number) =>
        `Exibindo ${first}-${last} de ${total}`,
    },
    terms: {
      none: 'Nao informado',
      priorities: {
        high: 'Alta',
        low: 'Baixa',
        medium: 'Media',
        urgent: 'Urgente',
      } satisfies Record<OccurrencePriority, string>,
      types: {
        complaint: 'Reclamacao',
        incident: 'Incidente',
        maintenance: 'Manutencao',
        noise: 'Barulho',
        other: 'Outra',
        request: 'Solicitacao',
        security: 'Seguranca',
      } satisfies Record<OccurrenceType, string>,
    },
  },
} as const

export function getOccurrenceCopy(locale: AppLocale) {
  return occurrenceCopies[normalizeAppLocale(locale)]
}
