import { normalizeAppLocale, type AppLocale } from '../../i18n'
import type { VehicleAuthorizationStatus, VehicleType } from '../../lib/api/vehicles'

const vehicleCopies = {
  'en-US': {
    detail: {
      actions: {
        authorize: 'Authorize',
        back: 'Back to vehicles',
        deny: 'Deny',
        edit: 'Edit vehicle',
      },
      audit: {
        archivedAt: 'Archived at',
        createdAt: 'Created at',
        updatedAt: 'Updated at',
      },
      documentsTitle: 'Documents',
      emptyRelationship: 'This relationship will appear here when connected.',
      error: 'Could not load vehicle details.',
      labels: {
        authorizationStatus: 'Authorization',
        brandModel: 'Brand / model',
        color: 'Color',
        contract: 'Contract',
        notes: 'Notes',
        parkingAllocationNotes: 'Parking notes',
        parkingSpaceIdentifier: 'Parking space',
        plate: 'Plate',
        property: 'Property',
        resident: 'Resident',
        type: 'Type',
        year: 'Year',
      },
      loading: 'Loading vehicle details...',
      noNotes: 'No notes registered.',
      pageDescription: 'Review ownership, authorization, parking allocation, and history.',
      relationshipTitle: 'Relationships',
      relationships: {
        audit: 'Audit',
        timeline: 'Timeline',
      },
      summaryTitle: 'Vehicle summary',
    },
    form: {
      authorizationStatus: 'Authorization',
      authorizationStatusRequired: 'Select an authorization status.',
      cancel: 'Cancel',
      color: 'Color',
      contractId: 'Contract',
      identifiersSection: 'Linked records',
      metadataSection: 'Vehicle data',
      modeTitle: {
        create: 'Create vehicle',
        edit: 'Edit vehicle',
      },
      notes: 'Notes',
      ownerRequired: 'Enter a resident ID or a contract ID.',
      parkingAllocationNotes: 'Parking notes',
      parkingSection: 'Parking allocation',
      parkingSpaceIdentifier: 'Parking identifier',
      plate: 'Plate',
      plateRequired: 'Enter the vehicle plate.',
      propertyId: 'Property',
      residentId: 'Resident',
      submitCreate: 'Create vehicle',
      submitEdit: 'Save changes',
      type: 'Type',
      typeRequired: 'Select the vehicle type.',
      validationTitle: 'Review the highlighted fields',
      vehicleBrand: 'Brand',
      vehicleModel: 'Model',
      year: 'Year',
      yearInvalid: 'Enter a valid vehicle year.',
    },
    list: {
      activeFilters: (count: number) => `${count} active filters`,
      add: 'Add vehicle',
      allParking: 'All parking',
      allStatuses: 'All',
      allTypes: 'All',
      archive: 'Archive',
      authorize: 'Authorize',
      clearFilters: 'Clear filters',
      columns: {
        actions: 'Actions',
        authorizationStatus: 'Authorization',
        owner: 'Owner',
        parking: 'Parking',
        property: 'Property',
        type: 'Type',
        vehicle: 'Vehicle',
      },
      contractId: 'Contract ID',
      deny: 'Deny',
      edit: 'Edit',
      empty: 'No vehicles found.',
      error: 'Could not load vehicles.',
      filters: 'Filters',
      hasParking: 'With parking',
      includeArchived: 'Include archived',
      loading: 'Loading vehicles...',
      noParking: 'No parking',
      pageDescription: 'Manage resident vehicles, authorization, and parking spaces.',
      pageTitle: 'Vehicles',
      parkingSpaceIdentifier: 'Parking identifier',
      plate: 'Plate',
      propertyId: 'Property ID',
      residentId: 'Resident ID',
      restore: 'Restore',
      search: 'Search vehicles',
      searchPlaceholder: 'Search by plate, resident, property, contract, brand, or model',
      status: {
        archived: 'Archived',
        authorized: 'Authorized',
        denied: 'Denied',
        inactive: 'Inactive',
        pending: 'Pending',
      } satisfies Record<VehicleAuthorizationStatus, string>,
      view: 'View details',
    },
    pagination: {
      next: 'Next',
      page: (page: number, totalPages: number) => `Page ${page} of ${totalPages}`,
      previous: 'Previous',
      range: (first: number, last: number, total: number) => `Showing ${first}-${last} of ${total}`,
    },
    terms: {
      none: 'Not informed',
      parking: {
        false: 'No parking',
        true: 'With parking',
      },
      types: {
        bicycle: 'Bicycle',
        car: 'Car',
        motorcycle: 'Motorcycle',
        other: 'Other',
        truck: 'Truck',
        van: 'Van',
      } satisfies Record<VehicleType, string>,
    },
  },
  'pt-BR': {
    detail: {
      actions: {
        authorize: 'Autorizar',
        back: 'Voltar para veiculos',
        deny: 'Negar',
        edit: 'Editar veiculo',
      },
      audit: {
        archivedAt: 'Arquivado em',
        createdAt: 'Criado em',
        updatedAt: 'Atualizado em',
      },
      documentsTitle: 'Documentos',
      emptyRelationship: 'Este relacionamento aparecera aqui quando estiver conectado.',
      error: 'Nao foi possivel carregar os detalhes do veiculo.',
      labels: {
        authorizationStatus: 'Autorizacao',
        brandModel: 'Marca / modelo',
        color: 'Cor',
        contract: 'Contrato',
        notes: 'Observacoes',
        parkingAllocationNotes: 'Observacoes da vaga',
        parkingSpaceIdentifier: 'Vaga',
        plate: 'Placa',
        property: 'Imovel',
        resident: 'Morador',
        type: 'Tipo',
        year: 'Ano',
      },
      loading: 'Carregando detalhes do veiculo...',
      noNotes: 'Nenhuma observacao cadastrada.',
      pageDescription: 'Revise propriedade, autorizacao, vaga e historico.',
      relationshipTitle: 'Relacionamentos',
      relationships: {
        audit: 'Auditoria',
        timeline: 'Timeline',
      },
      summaryTitle: 'Resumo do veiculo',
    },
    form: {
      authorizationStatus: 'Autorizacao',
      authorizationStatusRequired: 'Selecione o status de autorizacao.',
      cancel: 'Cancelar',
      color: 'Cor',
      contractId: 'Contrato',
      identifiersSection: 'Registros vinculados',
      metadataSection: 'Dados do veiculo',
      modeTitle: {
        create: 'Criar veiculo',
        edit: 'Editar veiculo',
      },
      notes: 'Observacoes',
      ownerRequired: 'Informe um ID de morador ou de contrato.',
      parkingAllocationNotes: 'Observacoes da vaga',
      parkingSection: 'Vaga de garagem',
      parkingSpaceIdentifier: 'Identificador da vaga',
      plate: 'Placa',
      plateRequired: 'Informe a placa do veiculo.',
      propertyId: 'Imovel',
      residentId: 'Morador',
      submitCreate: 'Criar veiculo',
      submitEdit: 'Salvar alteracoes',
      type: 'Tipo',
      typeRequired: 'Selecione o tipo de veiculo.',
      validationTitle: 'Revise os campos destacados',
      vehicleBrand: 'Marca',
      vehicleModel: 'Modelo',
      year: 'Ano',
      yearInvalid: 'Informe um ano valido.',
    },
    list: {
      activeFilters: (count: number) => `${count} filtros ativos`,
      add: 'Adicionar veiculo',
      allParking: 'Todas as vagas',
      allStatuses: 'Todos',
      allTypes: 'Todos',
      archive: 'Arquivar',
      authorize: 'Autorizar',
      clearFilters: 'Limpar filtros',
      columns: {
        actions: 'Acoes',
        authorizationStatus: 'Autorizacao',
        owner: 'Responsavel',
        parking: 'Vaga',
        property: 'Imovel',
        type: 'Tipo',
        vehicle: 'Veiculo',
      },
      contractId: 'ID do contrato',
      deny: 'Negar',
      edit: 'Editar',
      empty: 'Nenhum veiculo encontrado.',
      error: 'Nao foi possivel carregar os veiculos.',
      filters: 'Filtros',
      hasParking: 'Com vaga',
      includeArchived: 'Incluir arquivados',
      loading: 'Carregando veiculos...',
      noParking: 'Sem vaga',
      pageDescription: 'Gerencie veiculos de moradores, autorizacao e vagas de garagem.',
      pageTitle: 'Veiculos',
      parkingSpaceIdentifier: 'Identificador da vaga',
      plate: 'Placa',
      propertyId: 'ID do imovel',
      residentId: 'ID do morador',
      restore: 'Restaurar',
      search: 'Buscar veiculos',
      searchPlaceholder: 'Busque por placa, morador, imovel, contrato, marca ou modelo',
      status: {
        archived: 'Arquivado',
        authorized: 'Autorizado',
        denied: 'Negado',
        inactive: 'Inativo',
        pending: 'Pendente',
      } satisfies Record<VehicleAuthorizationStatus, string>,
      view: 'Ver detalhes',
    },
    pagination: {
      next: 'Proxima',
      page: (page: number, totalPages: number) => `Pagina ${page} de ${totalPages}`,
      previous: 'Anterior',
      range: (first: number, last: number, total: number) =>
        `Exibindo ${first}-${last} de ${total}`,
    },
    terms: {
      none: 'Nao informado',
      parking: {
        false: 'Sem vaga',
        true: 'Com vaga',
      },
      types: {
        bicycle: 'Bicicleta',
        car: 'Carro',
        motorcycle: 'Moto',
        other: 'Outro',
        truck: 'Caminhao',
        van: 'Van',
      } satisfies Record<VehicleType, string>,
    },
  },
} as const

export function getVehicleCopy(locale: AppLocale) {
  return vehicleCopies[normalizeAppLocale(locale)]
}
