import { normalizeAppLocale, type AppLocale } from '../../i18n'
import type {
  PaymentMethod,
  PaymentReconciliationStatus,
  PaymentStatus,
} from '../../lib/api/payments'

const paymentCopies = {
  'en-US': {
    detail: {
      actions: {
        back: 'Back to payments',
        edit: 'Edit payment',
        instructions: 'Generate instructions',
        reverse: 'Reverse',
        settle: 'Record settlement',
      },
      audit: {
        archivedAt: 'Archived at',
        createdAt: 'Created at',
        updatedAt: 'Updated at',
      },
      documentsTitle: 'Receipts',
      emptyRelationship: 'This relationship will appear here when connected.',
      emptyTransactions: 'No settlements recorded.',
      error: 'Could not load payment details.',
      labels: {
        amount: 'Amount',
        balance: 'Balance',
        contract: 'Contract',
        description: 'Description',
        discount: 'Discount',
        dueDate: 'Due date',
        grossAmount: 'Gross amount',
        method: 'Method',
        notes: 'Notes',
        penalty: 'Penalty',
        property: 'Property',
        reconciliation: 'Reconciliation',
        resident: 'Resident',
        settledAmount: 'Settled',
        status: 'Status',
      },
      loading: 'Loading payment details...',
      noNotes: 'No notes registered.',
      pageDescription: 'Review charge, settlement, reconciliation, and mocked provider data.',
      relationshipTitle: 'Relationships',
      reversed: 'Reversed',
      summaryTitle: 'Payment summary',
      transactionsTitle: 'Settlements',
    },
    form: {
      amount: 'Amount',
      amountRequired: 'Enter a valid amount.',
      cancel: 'Cancel',
      contractId: 'Contract ID',
      description: 'Description',
      discountAmount: 'Discount',
      dueDate: 'Due date',
      dueDateRequired: 'Enter the due date.',
      financialSection: 'Financial values',
      identifiersSection: 'Linked records',
      modeTitle: {
        create: 'Create payment',
        edit: 'Edit payment',
      },
      notes: 'Notes',
      penaltyAmount: 'Penalty',
      preferredMethod: 'Preferred method',
      preferredMethodRequired: 'Select a payment method.',
      propertyId: 'Property ID',
      reconciliationStatus: 'Reconciliation status',
      reconciliationStatusRequired: 'Select the reconciliation status.',
      residentId: 'Resident ID',
      submitCreate: 'Create payment',
      submitEdit: 'Save changes',
      title: 'Title',
      titleRequired: 'Enter a title.',
      utilityAccountId: 'Utility account ID',
      validationTitle: 'Review the highlighted fields',
    },
    instructions: {
      approvalUrl: 'Approval URL',
      barcode: 'Barcode',
      boleto: 'Boleto',
      cancel: 'Close',
      copyPasteCode: 'Copy and paste code',
      dueDate: 'Due date',
      expiresAt: 'Expires at',
      generate: 'Generate instructions',
      linhaDigitavel: 'Linha digitavel',
      noOutput: 'Choose a provider to generate mocked instructions.',
      payer: 'Payer',
      payPal: 'PayPal',
      paymentIntentId: 'Payment intent',
      pix: 'Pix',
      provider: 'Provider',
      providerReference: 'Provider reference',
      qrPayload: 'QR payload',
      status: 'Status',
      title: 'Payment instructions',
      unknown: 'Provider instructions',
    },
    list: {
      activeFilters: (count: number) => `${count} active filters`,
      add: 'Add payment',
      allStatuses: 'All',
      archive: 'Archive',
      cancel: 'Cancel',
      clearFilters: 'Clear filters',
      columns: {
        actions: 'Actions',
        amount: 'Amount',
        balance: 'Balance',
        dueDate: 'Due date',
        method: 'Method',
        payment: 'Payment',
        status: 'Status',
      },
      dueFrom: 'Due from',
      dueTo: 'Due to',
      edit: 'Edit',
      empty: 'No payments found.',
      error: 'Could not load payments.',
      filters: 'Filters',
      instructions: 'Instructions',
      loading: 'Loading payments...',
      overdueOnly: 'Overdue only',
      pageDescription: 'Manage charges, due dates, settlement, receipts, and reconciliation.',
      pageTitle: 'Payments',
      restore: 'Restore',
      search: 'Search payments',
      searchPlaceholder: 'Search by title, payer, property, or contract',
      settle: 'Settle',
      status: {
        archived: 'Archived',
        cancelled: 'Cancelled',
        disputed: 'Disputed',
        overdue: 'Overdue',
        paid: 'Paid',
        'partially-paid': 'Partially paid',
        pending: 'Pending',
      } satisfies Record<PaymentStatus, string>,
      view: 'View details',
    },
    pagination: {
      next: 'Next',
      page: (page: number, totalPages: number) => `Page ${page} of ${totalPages}`,
      previous: 'Previous',
      range: (first: number, last: number, total: number) => `Showing ${first}-${last} of ${total}`,
    },
    settlement: {
      amount: 'Amount',
      amountRequired: 'Enter a valid settlement amount.',
      bankReference: 'Bank reference',
      cancel: 'Cancel',
      method: 'Method',
      methodRequired: 'Select a method.',
      notes: 'Notes',
      providerCode: 'Provider code',
      providerReference: 'Provider reference',
      receiptDocumentId: 'Receipt document ID',
      settledOn: 'Settled on',
      settledOnRequired: 'Enter the settlement date.',
      submit: 'Record settlement',
      title: 'Record settlement',
      validationTitle: 'Review the highlighted fields',
    },
    terms: {
      methods: {
        'bank-transfer': 'Bank transfer',
        boleto: 'Boleto',
        card: 'Card',
        cash: 'Cash',
        other: 'Other',
        paypal: 'PayPal',
        pix: 'Pix',
      } satisfies Record<PaymentMethod, string>,
      none: 'Not informed',
      reconciliationStatuses: {
        failed: 'Failed',
        matched: 'Matched',
        'manual-review': 'Manual review',
        'not-required': 'Not required',
        pending: 'Pending',
      } satisfies Record<PaymentReconciliationStatus, string>,
    },
  },
  'pt-BR': {
    detail: {
      actions: {
        back: 'Voltar para pagamentos',
        edit: 'Editar pagamento',
        instructions: 'Gerar instrucoes',
        reverse: 'Estornar',
        settle: 'Registrar recebimento',
      },
      audit: {
        archivedAt: 'Arquivado em',
        createdAt: 'Criado em',
        updatedAt: 'Atualizado em',
      },
      documentsTitle: 'Recibos',
      emptyRelationship: 'Este relacionamento aparecera aqui quando estiver conectado.',
      emptyTransactions: 'Nenhum recebimento registrado.',
      error: 'Nao foi possivel carregar os detalhes do pagamento.',
      labels: {
        amount: 'Valor',
        balance: 'Saldo',
        contract: 'Contrato',
        description: 'Descricao',
        discount: 'Desconto',
        dueDate: 'Vencimento',
        grossAmount: 'Valor bruto',
        method: 'Metodo',
        notes: 'Observacoes',
        penalty: 'Multa',
        property: 'Imovel',
        reconciliation: 'Conciliacao',
        resident: 'Morador',
        settledAmount: 'Recebido',
        status: 'Status',
      },
      loading: 'Carregando detalhes do pagamento...',
      noNotes: 'Nenhuma observacao cadastrada.',
      pageDescription: 'Revise cobranca, recebimento, conciliacao e dados do provedor mock.',
      relationshipTitle: 'Relacionamentos',
      reversed: 'Estornado',
      summaryTitle: 'Resumo do pagamento',
      transactionsTitle: 'Recebimentos',
    },
    form: {
      amount: 'Valor',
      amountRequired: 'Informe um valor valido.',
      cancel: 'Cancelar',
      contractId: 'ID do contrato',
      description: 'Descricao',
      discountAmount: 'Desconto',
      dueDate: 'Vencimento',
      dueDateRequired: 'Informe a data de vencimento.',
      financialSection: 'Valores financeiros',
      identifiersSection: 'Registros vinculados',
      modeTitle: {
        create: 'Criar pagamento',
        edit: 'Editar pagamento',
      },
      notes: 'Observacoes',
      penaltyAmount: 'Multa',
      preferredMethod: 'Metodo preferencial',
      preferredMethodRequired: 'Selecione um metodo de pagamento.',
      propertyId: 'ID do imovel',
      reconciliationStatus: 'Status da conciliacao',
      reconciliationStatusRequired: 'Selecione o status da conciliacao.',
      residentId: 'ID do morador',
      submitCreate: 'Criar pagamento',
      submitEdit: 'Salvar alteracoes',
      title: 'Titulo',
      titleRequired: 'Informe um titulo.',
      utilityAccountId: 'ID da conta de consumo',
      validationTitle: 'Revise os campos destacados',
    },
    instructions: {
      approvalUrl: 'URL de aprovacao',
      barcode: 'Codigo de barras',
      boleto: 'Boleto',
      cancel: 'Fechar',
      copyPasteCode: 'Codigo copia e cola',
      dueDate: 'Vencimento',
      expiresAt: 'Expira em',
      generate: 'Gerar instrucoes',
      linhaDigitavel: 'Linha digitavel',
      noOutput: 'Escolha um provedor para gerar instrucoes mockadas.',
      payer: 'Pagador',
      payPal: 'PayPal',
      paymentIntentId: 'Intencao de pagamento',
      pix: 'Pix',
      provider: 'Provedor',
      providerReference: 'Referencia do provedor',
      qrPayload: 'Payload QR',
      status: 'Status',
      title: 'Instrucoes de pagamento',
      unknown: 'Instrucoes do provedor',
    },
    list: {
      activeFilters: (count: number) => `${count} filtros ativos`,
      add: 'Adicionar pagamento',
      allStatuses: 'Todos',
      archive: 'Arquivar',
      cancel: 'Cancelar',
      clearFilters: 'Limpar filtros',
      columns: {
        actions: 'Acoes',
        amount: 'Valor',
        balance: 'Saldo',
        dueDate: 'Vencimento',
        method: 'Metodo',
        payment: 'Pagamento',
        status: 'Status',
      },
      dueFrom: 'Vence de',
      dueTo: 'Vence ate',
      edit: 'Editar',
      empty: 'Nenhum pagamento encontrado.',
      error: 'Nao foi possivel carregar os pagamentos.',
      filters: 'Filtros',
      instructions: 'Instrucoes',
      loading: 'Carregando pagamentos...',
      overdueOnly: 'Somente atrasados',
      pageDescription: 'Gerencie cobrancas, vencimentos, recebimentos, recibos e conciliacao.',
      pageTitle: 'Pagamentos',
      restore: 'Restaurar',
      search: 'Buscar pagamentos',
      searchPlaceholder: 'Busque por titulo, pagador, imovel ou contrato',
      settle: 'Receber',
      status: {
        archived: 'Arquivado',
        cancelled: 'Cancelado',
        disputed: 'Em disputa',
        overdue: 'Em atraso',
        paid: 'Pago',
        'partially-paid': 'Parcialmente pago',
        pending: 'Pendente',
      } satisfies Record<PaymentStatus, string>,
      view: 'Ver detalhes',
    },
    pagination: {
      next: 'Proxima',
      page: (page: number, totalPages: number) => `Pagina ${page} de ${totalPages}`,
      previous: 'Anterior',
      range: (first: number, last: number, total: number) =>
        `Exibindo ${first}-${last} de ${total}`,
    },
    settlement: {
      amount: 'Valor',
      amountRequired: 'Informe um valor recebido valido.',
      bankReference: 'Referencia bancaria',
      cancel: 'Cancelar',
      method: 'Metodo',
      methodRequired: 'Selecione um metodo.',
      notes: 'Observacoes',
      providerCode: 'Codigo do provedor',
      providerReference: 'Referencia do provedor',
      receiptDocumentId: 'ID do recibo',
      settledOn: 'Recebido em',
      settledOnRequired: 'Informe a data do recebimento.',
      submit: 'Registrar recebimento',
      title: 'Registrar recebimento',
      validationTitle: 'Revise os campos destacados',
    },
    terms: {
      methods: {
        'bank-transfer': 'Transferencia bancaria',
        boleto: 'Boleto',
        card: 'Cartao',
        cash: 'Dinheiro',
        other: 'Outro',
        paypal: 'PayPal',
        pix: 'Pix',
      } satisfies Record<PaymentMethod, string>,
      none: 'Nao informado',
      reconciliationStatuses: {
        failed: 'Falhou',
        matched: 'Conciliado',
        'manual-review': 'Revisao manual',
        'not-required': 'Nao requer',
        pending: 'Pendente',
      } satisfies Record<PaymentReconciliationStatus, string>,
    },
  },
} as const

export function getPaymentCopy(locale: AppLocale) {
  return paymentCopies[normalizeAppLocale(locale)]
}
