import { normalizeAppLocale, type AppLocale } from '../../i18n'
import type {
  UtilityAccountResponsibility,
  UtilityAccountStatus,
  UtilityAccountType,
  UtilityPaymentMethod,
} from '../../lib/api/utilityAccounts'

const utilityAccountCopies = {
  'en-US': {
    detail: {
      actions: {
        back: 'Back to utility accounts',
        cancel: 'Cancel account',
        edit: 'Edit utility account',
        markPaid: 'Mark paid',
      },
      audit: {
        archivedAt: 'Archived at',
        createdAt: 'Created at',
        updatedAt: 'Updated at',
      },
      billDocumentsTitle: 'Bills',
      emptyRelationship: 'This relationship will appear here when connected.',
      error: 'Could not load utility account details.',
      labels: {
        amount: 'Amount',
        balance: 'Balance',
        bankReference: 'Bank reference',
        billingPeriod: 'Billing period',
        contract: 'Contract',
        description: 'Description',
        dueDate: 'Due date',
        paidAmount: 'Paid amount',
        paidOn: 'Paid on',
        paymentMethod: 'Payment method',
        property: 'Property',
        receiptDocuments: 'Receipts',
        resident: 'Resident',
        responsibility: 'Responsibility',
        status: 'Status',
        type: 'Type',
      },
      loading: 'Loading utility account details...',
      noNotes: 'No description registered.',
      pageDescription: 'Review billing period, responsibility, payment, documents, and history.',
      receiptDocumentsTitle: 'Receipts',
      relationshipTitle: 'Relationships',
      relationships: {
        audit: 'Audit',
        timeline: 'Timeline',
      },
      summaryTitle: 'Utility account summary',
    },
    documentAttachment: {
      clear: 'Clear document',
      loading: 'Loading documents...',
      lookupError: 'Could not load documents. Enter the document ID manually.',
      manualDocumentId: 'Document ID',
      manualDocumentIdPlaceholder: 'Paste the document ID',
      manualFallback: 'Enter a document ID from the Documents module.',
      search: 'Search documents',
      searchPlaceholder: 'Search by title, file, or category',
      selectPlaceholder: 'Select a document',
      selectedId: (documentId: string) => `Selected document ${documentId}`,
    },
    form: {
      amount: 'Amount',
      amountRequired: 'Enter a valid amount.',
      billDocumentId: 'Bill document',
      billingPeriodEnd: 'Billing end',
      billingPeriodEndRequired: 'Enter the billing end date.',
      billingPeriodStart: 'Billing start',
      billingPeriodStartRequired: 'Enter the billing start date.',
      cancel: 'Cancel',
      contractId: 'Contract ID',
      description: 'Description',
      documentHint: 'Select an existing document or enter a document ID from Documents.',
      documentsSection: 'Documents',
      dueDate: 'Due date',
      dueDateRequired: 'Enter the due date.',
      financialSection: 'Billing values',
      identifiersSection: 'Linked records',
      modeTitle: {
        create: 'Create utility account',
        edit: 'Edit utility account',
      },
      propertyId: 'Property ID',
      residentId: 'Resident ID',
      responsibility: 'Responsibility',
      responsibilityRequired: 'Select the responsible party.',
      submitCreate: 'Create utility account',
      submitEdit: 'Save changes',
      title: 'Title',
      titleRequired: 'Enter a title.',
      type: 'Type',
      typeRequired: 'Select the utility type.',
      validationTitle: 'Review the highlighted fields',
    },
    list: {
      activeFilters: (count: number) => `${count} active filters`,
      add: 'Add utility account',
      allResponsibilities: 'All',
      allStatuses: 'All',
      allTypes: 'All',
      archive: 'Archive',
      cancel: 'Cancel',
      clearFilters: 'Clear filters',
      columns: {
        actions: 'Actions',
        amount: 'Amount',
        balance: 'Balance',
        dueDate: 'Due date',
        responsibility: 'Responsibility',
        status: 'Status',
        type: 'Type',
        utilityAccount: 'Utility account',
      },
      billingFrom: 'Billing from',
      billingTo: 'Billing to',
      contractId: 'Contract ID',
      dueFrom: 'Due from',
      dueTo: 'Due to',
      edit: 'Edit',
      empty: 'No utility accounts found.',
      error: 'Could not load utility accounts.',
      filters: 'Filters',
      includeArchived: 'Include archived',
      loading: 'Loading utility accounts...',
      markPaid: 'Pay',
      pageDescription: 'Manage utility bills, responsibility, due dates, documents, and payments.',
      pageTitle: 'Utility accounts',
      propertyId: 'Property ID',
      restore: 'Restore',
      search: 'Search utility accounts',
      searchPlaceholder: 'Search by title, property, contract, resident, or reference',
      status: {
        archived: 'Archived',
        cancelled: 'Cancelled',
        disputed: 'Disputed',
        open: 'Open',
        overdue: 'Overdue',
        paid: 'Paid',
      } satisfies Record<UtilityAccountStatus, string>,
      view: 'View details',
    },
    markPaid: {
      amount: 'Paid amount',
      amountRequired: 'Enter a valid paid amount.',
      bankReference: 'Bank reference',
      cancel: 'Cancel',
      notes: 'Notes',
      paidOn: 'Paid on',
      paidOnRequired: 'Enter the payment date.',
      paymentMethod: 'Payment method',
      receiptDocumentId: 'Receipt document',
      submit: 'Mark paid',
      title: 'Mark utility account paid',
      validationTitle: 'Review the highlighted fields',
    },
    pagination: {
      next: 'Next',
      page: (page: number, totalPages: number) => `Page ${page} of ${totalPages}`,
      previous: 'Previous',
      range: (first: number, last: number, total: number) => `Showing ${first}-${last} of ${total}`,
    },
    terms: {
      methods: {
        'bank-transfer': 'Bank transfer',
        boleto: 'Boleto',
        card: 'Card',
        cash: 'Cash',
        other: 'Other',
        paypal: 'PayPal',
        pix: 'Pix',
      } satisfies Record<UtilityPaymentMethod, string>,
      none: 'Not informed',
      responsibilities: {
        contract: 'Contract',
        organization: 'Organization',
        other: 'Other',
        owner: 'Owner',
        property: 'Property',
        resident: 'Resident',
      } satisfies Record<UtilityAccountResponsibility, string>,
      types: {
        'condominium-fee': 'Condominium fee',
        electricity: 'Electricity',
        gas: 'Gas',
        insurance: 'Insurance',
        internet: 'Internet',
        iptu: 'IPTU',
        other: 'Other',
        water: 'Water',
      } satisfies Record<UtilityAccountType, string>,
    },
  },
  'pt-BR': {
    detail: {
      actions: {
        back: 'Voltar para contas de consumo',
        cancel: 'Cancelar conta',
        edit: 'Editar conta de consumo',
        markPaid: 'Marcar como paga',
      },
      audit: {
        archivedAt: 'Arquivada em',
        createdAt: 'Criada em',
        updatedAt: 'Atualizada em',
      },
      billDocumentsTitle: 'Faturas',
      emptyRelationship: 'Este relacionamento aparecera aqui quando estiver conectado.',
      error: 'Nao foi possivel carregar os detalhes da conta de consumo.',
      labels: {
        amount: 'Valor',
        balance: 'Saldo',
        bankReference: 'Referencia bancaria',
        billingPeriod: 'Periodo de consumo',
        contract: 'Contrato',
        description: 'Descricao',
        dueDate: 'Vencimento',
        paidAmount: 'Valor pago',
        paidOn: 'Pago em',
        paymentMethod: 'Metodo de pagamento',
        property: 'Imovel',
        receiptDocuments: 'Recibos',
        resident: 'Morador',
        responsibility: 'Responsavel',
        status: 'Status',
        type: 'Tipo',
      },
      loading: 'Carregando detalhes da conta de consumo...',
      noNotes: 'Nenhuma descricao cadastrada.',
      pageDescription: 'Revise periodo, responsavel, pagamento, documentos e historico.',
      receiptDocumentsTitle: 'Recibos',
      relationshipTitle: 'Relacionamentos',
      relationships: {
        audit: 'Auditoria',
        timeline: 'Timeline',
      },
      summaryTitle: 'Resumo da conta de consumo',
    },
    documentAttachment: {
      clear: 'Limpar documento',
      loading: 'Carregando documentos...',
      lookupError: 'Nao foi possivel carregar documentos. Informe o ID manualmente.',
      manualDocumentId: 'ID do documento',
      manualDocumentIdPlaceholder: 'Cole o ID do documento',
      manualFallback: 'Informe um ID de documento do modulo Documentos.',
      search: 'Buscar documentos',
      searchPlaceholder: 'Busque por titulo, arquivo ou categoria',
      selectPlaceholder: 'Selecione um documento',
      selectedId: (documentId: string) => `Documento selecionado ${documentId}`,
    },
    form: {
      amount: 'Valor',
      amountRequired: 'Informe um valor valido.',
      billDocumentId: 'Fatura',
      billingPeriodEnd: 'Fim do periodo',
      billingPeriodEndRequired: 'Informe o fim do periodo.',
      billingPeriodStart: 'Inicio do periodo',
      billingPeriodStartRequired: 'Informe o inicio do periodo.',
      cancel: 'Cancelar',
      contractId: 'ID do contrato',
      description: 'Descricao',
      documentHint: 'Selecione um documento existente ou informe um ID do modulo Documentos.',
      documentsSection: 'Documentos',
      dueDate: 'Vencimento',
      dueDateRequired: 'Informe a data de vencimento.',
      financialSection: 'Valores da conta',
      identifiersSection: 'Registros vinculados',
      modeTitle: {
        create: 'Criar conta de consumo',
        edit: 'Editar conta de consumo',
      },
      propertyId: 'ID do imovel',
      residentId: 'ID do morador',
      responsibility: 'Responsavel',
      responsibilityRequired: 'Selecione o responsavel.',
      submitCreate: 'Criar conta de consumo',
      submitEdit: 'Salvar alteracoes',
      title: 'Titulo',
      titleRequired: 'Informe um titulo.',
      type: 'Tipo',
      typeRequired: 'Selecione o tipo de conta.',
      validationTitle: 'Revise os campos destacados',
    },
    list: {
      activeFilters: (count: number) => `${count} filtros ativos`,
      add: 'Adicionar conta',
      allResponsibilities: 'Todos',
      allStatuses: 'Todos',
      allTypes: 'Todos',
      archive: 'Arquivar',
      cancel: 'Cancelar',
      clearFilters: 'Limpar filtros',
      columns: {
        actions: 'Acoes',
        amount: 'Valor',
        balance: 'Saldo',
        dueDate: 'Vencimento',
        responsibility: 'Responsavel',
        status: 'Status',
        type: 'Tipo',
        utilityAccount: 'Conta de consumo',
      },
      billingFrom: 'Consumo de',
      billingTo: 'Consumo ate',
      contractId: 'ID do contrato',
      dueFrom: 'Vence de',
      dueTo: 'Vence ate',
      edit: 'Editar',
      empty: 'Nenhuma conta de consumo encontrada.',
      error: 'Nao foi possivel carregar as contas de consumo.',
      filters: 'Filtros',
      includeArchived: 'Incluir arquivadas',
      loading: 'Carregando contas de consumo...',
      markPaid: 'Pagar',
      pageDescription:
        'Gerencie contas de consumo, responsaveis, vencimentos, documentos e pagamentos.',
      pageTitle: 'Contas de Consumo',
      propertyId: 'ID do imovel',
      restore: 'Restaurar',
      search: 'Buscar contas de consumo',
      searchPlaceholder: 'Busque por titulo, imovel, contrato, morador ou referencia',
      status: {
        archived: 'Arquivada',
        cancelled: 'Cancelada',
        disputed: 'Em disputa',
        open: 'Aberta',
        overdue: 'Em atraso',
        paid: 'Paga',
      } satisfies Record<UtilityAccountStatus, string>,
      view: 'Ver detalhes',
    },
    markPaid: {
      amount: 'Valor pago',
      amountRequired: 'Informe um valor pago valido.',
      bankReference: 'Referencia bancaria',
      cancel: 'Cancelar',
      notes: 'Observacoes',
      paidOn: 'Pago em',
      paidOnRequired: 'Informe a data do pagamento.',
      paymentMethod: 'Metodo de pagamento',
      receiptDocumentId: 'Recibo',
      submit: 'Marcar como paga',
      title: 'Marcar conta como paga',
      validationTitle: 'Revise os campos destacados',
    },
    pagination: {
      next: 'Proxima',
      page: (page: number, totalPages: number) => `Pagina ${page} de ${totalPages}`,
      previous: 'Anterior',
      range: (first: number, last: number, total: number) =>
        `Exibindo ${first}-${last} de ${total}`,
    },
    terms: {
      methods: {
        'bank-transfer': 'Transferencia bancaria',
        boleto: 'Boleto',
        card: 'Cartao',
        cash: 'Dinheiro',
        other: 'Outro',
        paypal: 'PayPal',
        pix: 'Pix',
      } satisfies Record<UtilityPaymentMethod, string>,
      none: 'Nao informado',
      responsibilities: {
        contract: 'Contrato',
        organization: 'Organizacao',
        other: 'Outro',
        owner: 'Proprietario',
        property: 'Imovel',
        resident: 'Morador',
      } satisfies Record<UtilityAccountResponsibility, string>,
      types: {
        'condominium-fee': 'Condominio',
        electricity: 'Energia',
        gas: 'Gas',
        insurance: 'Seguro',
        internet: 'Internet',
        iptu: 'IPTU',
        other: 'Outro',
        water: 'Agua',
      } satisfies Record<UtilityAccountType, string>,
    },
  },
} as const

export function getUtilityAccountCopy(locale: AppLocale) {
  return utilityAccountCopies[normalizeAppLocale(locale)]
}
