import { normalizeAppLocale, type AppLocale } from '../../i18n'

const settingsCopies = {
  'en-US': {
    actions: {
      refresh: 'Refresh',
      removeLogo: 'Remove logo',
      resetBranding: 'Reset design',
      save: 'Save',
      uploadLogo: 'Upload logo',
    },
    branding: {
      accentColor: 'Accent color',
      accentForegroundColor: 'Accent text',
      displayName: 'Brand display name',
      logoAlt: 'Logo alt text',
      logoFile: 'Logo file',
      logoUrl: 'Logo URL',
      primaryColor: 'Primary color',
      primaryForegroundColor: 'Primary text',
      supportEmail: 'Support email',
      supportPhone: 'Support phone',
      supportUrl: 'Support URL',
      title: 'Branding and support',
    },
    catalogs: {
      code: 'Code',
      enabled: 'Enabled',
      en: 'English',
      pt: 'Portuguese',
      sortOrder: 'Order',
      title: 'Catalog labels',
    },
    common: {
      disabled: 'Disabled',
      enabled: 'Enabled',
      loading: 'Loading settings...',
      pageDescription:
        'Configure organization defaults, resident portal behavior, catalogs, notifications, security, and preferences.',
      pageTitle: 'Settings',
      validation: 'Review the highlighted fields.',
    },
    localization: {
      defaultLocale: 'Default locale',
      enabledLocales: 'Enabled locales',
      fallbackLocale: 'Fallback locale',
      preference: 'My locale',
      title: 'Localization',
    },
    notifications: {
      categories: 'Categories',
      channels: 'Channels',
      email: 'Email delivery',
      inApp: 'In-app delivery',
      title: 'Notification defaults',
      whatsapp: 'WhatsApp placeholder',
    },
    organization: {
      contactEmail: 'Contact email',
      contactPhone: 'Contact phone',
      contactWebsite: 'Contact website',
      currencyCode: 'Currency',
      displayName: 'Display name',
      name: 'Legal name',
      slug: 'Slug',
      timeZone: 'Time zone',
      title: 'Organization profile',
    },
    residentPortal: {
      allowDocumentUpload: 'Allow resident document uploads',
      allowOccurrenceCreation: 'Allow resident occurrence creation',
      allowProfileUpdateRequests: 'Allow profile update requests',
      isEnabled: 'Enable resident portal',
      title: 'Resident portal',
    },
    security: {
      mfaPolicy: 'MFA policy',
      minimumLength: 'Minimum password length',
      requireDigit: 'Require number',
      requireLowercase: 'Require lowercase',
      requireSymbol: 'Require symbol',
      requireUppercase: 'Require uppercase',
      sessionTimeoutMinutes: 'Session timeout (minutes)',
      title: 'Security policy',
    },
    tabs: {
      catalogs: 'Catalogs',
      localization: 'Localization',
      notifications: 'Notifications',
      organization: 'Organization',
      profile: 'Profile',
      residentPortal: 'Resident portal',
      security: 'Security',
      tenant: 'Tenant',
    },
    tenant: {
      allowOrganizationSwitching: 'Allow organization switching',
      requireActiveOrganization: 'Require active organization',
      strictTenantIsolation: 'Strict tenant isolation',
      title: 'Tenant behavior',
    },
  },
  'pt-BR': {
    actions: {
      refresh: 'Atualizar',
      removeLogo: 'Remover logo',
      resetBranding: 'Redefinir design',
      save: 'Salvar',
      uploadLogo: 'Enviar logo',
    },
    branding: {
      accentColor: 'Cor de destaque',
      accentForegroundColor: 'Texto do destaque',
      displayName: 'Nome da marca',
      logoAlt: 'Texto alternativo do logo',
      logoFile: 'Arquivo do logo',
      logoUrl: 'URL do logo',
      primaryColor: 'Cor primaria',
      primaryForegroundColor: 'Texto da cor primaria',
      supportEmail: 'E-mail de suporte',
      supportPhone: 'Telefone de suporte',
      supportUrl: 'URL de suporte',
      title: 'Marca e suporte',
    },
    catalogs: {
      code: 'Codigo',
      enabled: 'Ativo',
      en: 'Ingles',
      pt: 'Portugues',
      sortOrder: 'Ordem',
      title: 'Rotulos dos catalogos',
    },
    common: {
      disabled: 'Desativado',
      enabled: 'Ativado',
      loading: 'Carregando configuracoes...',
      pageDescription:
        'Configure organizacao, portal do morador, catalogos, notificacoes, seguranca e preferencias.',
      pageTitle: 'Configuracoes',
      validation: 'Revise os campos destacados.',
    },
    localization: {
      defaultLocale: 'Locale padrao',
      enabledLocales: 'Locales ativos',
      fallbackLocale: 'Locale de fallback',
      preference: 'Meu locale',
      title: 'Localizacao',
    },
    notifications: {
      categories: 'Categorias',
      channels: 'Canais',
      email: 'Envio por e-mail',
      inApp: 'Envio no aplicativo',
      title: 'Padroes de notificacao',
      whatsapp: 'Placeholder WhatsApp',
    },
    organization: {
      contactEmail: 'E-mail de contato',
      contactPhone: 'Telefone de contato',
      contactWebsite: 'Site de contato',
      currencyCode: 'Moeda',
      displayName: 'Nome exibido',
      name: 'Razao social',
      slug: 'Slug',
      timeZone: 'Fuso horario',
      title: 'Perfil da organizacao',
    },
    residentPortal: {
      allowDocumentUpload: 'Permitir envio de documentos pelo morador',
      allowOccurrenceCreation: 'Permitir abertura de ocorrencias pelo morador',
      allowProfileUpdateRequests: 'Permitir solicitacoes de alteracao cadastral',
      isEnabled: 'Ativar portal do morador',
      title: 'Portal do morador',
    },
    security: {
      mfaPolicy: 'Politica de MFA',
      minimumLength: 'Tamanho minimo da senha',
      requireDigit: 'Exigir numero',
      requireLowercase: 'Exigir minuscula',
      requireSymbol: 'Exigir simbolo',
      requireUppercase: 'Exigir maiuscula',
      sessionTimeoutMinutes: 'Expiracao da sessao (minutos)',
      title: 'Politica de seguranca',
    },
    tabs: {
      catalogs: 'Catalogos',
      localization: 'Localizacao',
      notifications: 'Notificacoes',
      organization: 'Organizacao',
      profile: 'Perfil',
      residentPortal: 'Portal do morador',
      security: 'Seguranca',
      tenant: 'Tenant',
    },
    tenant: {
      allowOrganizationSwitching: 'Permitir troca de organizacao',
      requireActiveOrganization: 'Exigir organizacao ativa',
      strictTenantIsolation: 'Isolamento tenant estrito',
      title: 'Comportamento tenant',
    },
  },
} as const

export function getSettingsCopy(locale: AppLocale) {
  return settingsCopies[normalizeAppLocale(locale)]
}
