import { normalizeAppLocale, type AppLocale } from '../../i18n'
import type {
  DocumentCategory,
  DocumentLinkedEntityType,
  DocumentStatus,
} from '../../lib/api/documents'

const documentCopies = {
  'en-US': {
    detail: {
      actions: {
        archive: 'Archive',
        back: 'Back to documents',
        download: 'Download current file',
        edit: 'Edit metadata',
        restore: 'Restore',
        uploadVersion: 'Upload new version',
      },
      audit: {
        archivedAt: 'Archived at',
        createdAt: 'Created at',
        updatedAt: 'Updated at',
        uploadedAt: 'Uploaded at',
      },
      columns: {
        file: 'File',
        notes: 'Notes',
        uploadedAt: 'Uploaded at',
        version: 'Version',
      },
      emptyLinks: 'No linked records.',
      emptyVersions: 'No versions found.',
      error: 'Could not load document details.',
      labels: {
        category: 'Category',
        currentVersion: 'Current version',
        description: 'Description',
        fileName: 'File name',
        fileType: 'File type',
        links: 'Links',
        size: 'Size',
        status: 'Status',
      },
      loading: 'Loading document details...',
      noDescription: 'No description registered.',
      noNotes: 'No notes registered.',
      pageDescription: 'Review document metadata, links, versions, and operational history.',
      relationships: {
        audit: 'Audit',
        timeline: 'Timeline',
      },
      relationshipTitle: 'Relationships',
      summaryTitle: 'Document summary',
      versionsTitle: 'Versions',
    },
    form: {
      addLink: 'Add link',
      cancel: 'Cancel',
      category: 'Category',
      categoryRequired: 'Select a category.',
      description: 'Description',
      entityId: 'Linked record ID',
      entityIdRequired: 'Enter the linked record ID.',
      entityType: 'Linked record type',
      entityTypeRequired: 'Select a linked record type.',
      file: 'File',
      fileRequired: 'Select a file.',
      linkLabel: 'Link label',
      linksSection: 'Links',
      metadataSection: 'Metadata',
      modeTitle: {
        create: 'Upload document',
        edit: 'Edit document metadata',
      },
      notes: 'Notes',
      removeLink: 'Remove link',
      submitCreate: 'Upload document',
      submitEdit: 'Save metadata',
      title: 'Title',
      titleRequired: 'Enter the document title.',
      validationTitle: 'Review the highlighted fields',
      versionNotes: 'Version notes',
      versionTitle: 'Upload new version',
    },
    list: {
      activeFilters: (count: number) => `${count} active filters`,
      add: 'Upload document',
      allCategories: 'All categories',
      allLinkedTypes: 'All linked types',
      archive: 'Archive',
      clearFilters: 'Clear filters',
      columns: {
        actions: 'Actions',
        category: 'Category',
        document: 'Document',
        links: 'Links',
        status: 'Status',
        uploadedAt: 'Uploaded at',
      },
      download: 'Download',
      edit: 'Edit',
      empty: 'No documents found.',
      error: 'Could not load documents.',
      filters: 'Filters',
      includeArchived: 'Include archived',
      linkedEntityId: 'Linked record ID',
      loading: 'Loading documents...',
      ownerId: 'Uploaded by user ID',
      pageDescription:
        'Manage files, document versions, metadata, and links across properties, contracts, and residents.',
      pageTitle: 'Documents',
      restore: 'Restore',
      search: 'Search documents',
      searchPlaceholder: 'Search by title, file, category, or link',
      uploadTo: 'Uploaded to',
      uploadedFrom: 'Uploaded from',
      view: 'View details',
    },
    pagination: {
      next: 'Next',
      page: (page: number, totalPages: number) => `Page ${page} of ${totalPages}`,
      previous: 'Previous',
      range: (first: number, last: number, total: number) => `Showing ${first}-${last} of ${total}`,
    },
    terms: {
      categories: {
        contract: 'Contract',
        general: 'General',
        inspection: 'Inspection',
        occurrence: 'Occurrence',
        other: 'Other',
        'payment-receipt': 'Payment receipt',
        pet: 'Pet',
        property: 'Property',
        resident: 'Resident',
        'utility-account': 'Utility account',
        vehicle: 'Vehicle',
      } satisfies Record<DocumentCategory, string>,
      entityTypes: {
        contract: 'Contract',
        inspection: 'Inspection',
        occurrence: 'Occurrence',
        payment: 'Payment',
        pet: 'Pet',
        property: 'Property',
        resident: 'Resident',
        'utility-account': 'Utility account',
        vehicle: 'Vehicle',
      } satisfies Record<DocumentLinkedEntityType, string>,
      linksCount: (count: number) => `${count} links`,
      sizeBytes: (size: string) => `${size}`,
      status: {
        active: 'Active',
        archived: 'Archived',
      } satisfies Record<DocumentStatus, string>,
      versionNumber: (version: number) => `Version ${version}`,
    },
  },
  'pt-BR': {
    detail: {
      actions: {
        archive: 'Arquivar',
        back: 'Voltar para documentos',
        download: 'Baixar arquivo atual',
        edit: 'Editar metadados',
        restore: 'Restaurar',
        uploadVersion: 'Enviar nova versao',
      },
      audit: {
        archivedAt: 'Arquivado em',
        createdAt: 'Criado em',
        updatedAt: 'Atualizado em',
        uploadedAt: 'Enviado em',
      },
      columns: {
        file: 'Arquivo',
        notes: 'Notas',
        uploadedAt: 'Enviado em',
        version: 'Versao',
      },
      emptyLinks: 'Nenhum registro vinculado.',
      emptyVersions: 'Nenhuma versao encontrada.',
      error: 'Nao foi possivel carregar os detalhes do documento.',
      labels: {
        category: 'Categoria',
        currentVersion: 'Versao atual',
        description: 'Descricao',
        fileName: 'Nome do arquivo',
        fileType: 'Tipo do arquivo',
        links: 'Vinculos',
        size: 'Tamanho',
        status: 'Status',
      },
      loading: 'Carregando detalhes do documento...',
      noDescription: 'Nenhuma descricao cadastrada.',
      noNotes: 'Nenhuma nota cadastrada.',
      pageDescription: 'Revise metadados, vinculos, versoes e historico operacional.',
      relationships: {
        audit: 'Auditoria',
        timeline: 'Timeline',
      },
      relationshipTitle: 'Relacionamentos',
      summaryTitle: 'Resumo do documento',
      versionsTitle: 'Versoes',
    },
    form: {
      addLink: 'Adicionar vinculo',
      cancel: 'Cancelar',
      category: 'Categoria',
      categoryRequired: 'Selecione uma categoria.',
      description: 'Descricao',
      entityId: 'ID do registro vinculado',
      entityIdRequired: 'Informe o ID do registro vinculado.',
      entityType: 'Tipo do registro vinculado',
      entityTypeRequired: 'Selecione o tipo do registro vinculado.',
      file: 'Arquivo',
      fileRequired: 'Selecione um arquivo.',
      linkLabel: 'Rotulo do vinculo',
      linksSection: 'Vinculos',
      metadataSection: 'Metadados',
      modeTitle: {
        create: 'Enviar documento',
        edit: 'Editar metadados do documento',
      },
      notes: 'Notas',
      removeLink: 'Remover vinculo',
      submitCreate: 'Enviar documento',
      submitEdit: 'Salvar metadados',
      title: 'Titulo',
      titleRequired: 'Informe o titulo do documento.',
      validationTitle: 'Revise os campos destacados',
      versionNotes: 'Notas da versao',
      versionTitle: 'Enviar nova versao',
    },
    list: {
      activeFilters: (count: number) => `${count} filtros ativos`,
      add: 'Enviar documento',
      allCategories: 'Todas as categorias',
      allLinkedTypes: 'Todos os tipos vinculados',
      archive: 'Arquivar',
      clearFilters: 'Limpar filtros',
      columns: {
        actions: 'Acoes',
        category: 'Categoria',
        document: 'Documento',
        links: 'Vinculos',
        status: 'Status',
        uploadedAt: 'Enviado em',
      },
      download: 'Baixar',
      edit: 'Editar',
      empty: 'Nenhum documento encontrado.',
      error: 'Nao foi possivel carregar os documentos.',
      filters: 'Filtros',
      includeArchived: 'Incluir arquivados',
      linkedEntityId: 'ID do registro vinculado',
      loading: 'Carregando documentos...',
      ownerId: 'ID do usuario que enviou',
      pageDescription:
        'Gerencie arquivos, versoes, metadados e vinculos de imoveis, contratos e moradores.',
      pageTitle: 'Documentos',
      restore: 'Restaurar',
      search: 'Buscar documentos',
      searchPlaceholder: 'Busque por titulo, arquivo, categoria ou vinculo',
      uploadTo: 'Enviado ate',
      uploadedFrom: 'Enviado de',
      view: 'Ver detalhes',
    },
    pagination: {
      next: 'Proxima',
      page: (page: number, totalPages: number) => `Pagina ${page} de ${totalPages}`,
      previous: 'Anterior',
      range: (first: number, last: number, total: number) =>
        `Exibindo ${first}-${last} de ${total}`,
    },
    terms: {
      categories: {
        contract: 'Contrato',
        general: 'Geral',
        inspection: 'Vistoria',
        occurrence: 'Ocorrencia',
        other: 'Outro',
        'payment-receipt': 'Recibo de pagamento',
        pet: 'Pet',
        property: 'Imovel',
        resident: 'Morador',
        'utility-account': 'Conta de consumo',
        vehicle: 'Veiculo',
      } satisfies Record<DocumentCategory, string>,
      entityTypes: {
        contract: 'Contrato',
        inspection: 'Vistoria',
        occurrence: 'Ocorrencia',
        payment: 'Pagamento',
        pet: 'Pet',
        property: 'Imovel',
        resident: 'Morador',
        'utility-account': 'Conta de consumo',
        vehicle: 'Veiculo',
      } satisfies Record<DocumentLinkedEntityType, string>,
      linksCount: (count: number) => `${count} vinculos`,
      sizeBytes: (size: string) => `${size}`,
      status: {
        active: 'Ativo',
        archived: 'Arquivado',
      } satisfies Record<DocumentStatus, string>,
      versionNumber: (version: number) => `Versao ${version}`,
    },
  },
} as const

export function getDocumentCopy(locale: AppLocale) {
  return documentCopies[normalizeAppLocale(locale)]
}
