import { normalizeAppLocale, type AppLocale } from '../../i18n'
import type {
  InspectionConditionRating,
  InspectionDocumentKind,
  InspectionStatus,
  InspectionType,
} from '../../lib/api/inspections'

const inspectionCopies = {
  'en-US': {
    detail: {
      actions: {
        back: 'Back to inspections',
        cancel: 'Cancel',
        complete: 'Complete',
        edit: 'Edit inspection',
        save: 'Save',
        start: 'Start',
      },
      audit: {
        archivedAt: 'Archived at',
        createdAt: 'Created at',
        updatedAt: 'Updated at',
      },
      checklist: {
        add: 'Add item',
        areaName: 'Area',
        conditionRating: 'Condition',
        delete: 'Delete',
        edit: 'Edit',
        empty: 'No checklist items yet.',
        save: 'Save item',
        itemName: 'Item',
        observations: 'Observations',
        required: 'Required',
        title: 'Checklist execution',
      },
      completedReportTitle: 'Completed report',
      documentsTitle: 'Photos and documents',
      emptyRelationship: 'This relationship will appear here when connected.',
      error: 'Could not load inspection details.',
      labels: {
        assignee: 'Assignee',
        cancelledAt: 'Cancelled at',
        cancellationReason: 'Cancellation reason',
        completedAt: 'Completed at',
        completionNotes: 'Completion notes',
        contract: 'Contract',
        notes: 'Notes',
        progress: 'Progress',
        property: 'Property',
        resident: 'Resident',
        scheduledAt: 'Scheduled at',
        startedAt: 'Started at',
        status: 'Status',
        type: 'Type',
      },
      loading: 'Loading inspection details...',
      noNotes: 'No notes registered.',
      pageDescription: 'Review schedule, checklist, attachments, signatures, and report data.',
      relationshipTitle: 'Relationships',
      relationships: {
        audit: 'Audit',
        timeline: 'Timeline',
      },
      signaturesTitle: 'Signature slots',
      summaryTitle: 'Inspection summary',
    },
    documentLink: {
      checklistItem: 'Checklist item',
      documentId: 'Document ID',
      kind: 'Kind',
      label: 'Label',
      link: 'Link document',
      submit: 'Link',
      title: 'Link photo or document',
    },
    form: {
      assigneeRequired: 'Select an assignee.',
      assignedUserId: 'Assignee',
      cancel: 'Cancel',
      contractId: 'Contract',
      metadataSection: 'Schedule',
      modeTitle: {
        create: 'Schedule inspection',
        edit: 'Edit inspection',
      },
      notes: 'Notes',
      propertyId: 'Property',
      propertyRequired: 'Select a property.',
      residentId: 'Resident',
      scheduledAt: 'Scheduled date',
      scheduledAtRequired: 'Enter the scheduled date.',
      signatureRole: 'Signature role',
      signatureRequired: 'Signature required',
      signatureSection: 'Signature slots',
      signatureSigner: 'Signer name',
      submitCreate: 'Schedule inspection',
      submitEdit: 'Save changes',
      title: 'Title',
      type: 'Type',
      typeRequired: 'Select the inspection type.',
      validationTitle: 'Review the highlighted fields',
    },
    list: {
      activeFilters: (count: number) => `${count} active filters`,
      add: 'Schedule inspection',
      allStatuses: 'All',
      allTypes: 'All',
      archive: 'Archive',
      cancel: 'Cancel',
      clearFilters: 'Clear filters',
      columns: {
        actions: 'Actions',
        assignee: 'Assignee',
        date: 'Date',
        progress: 'Progress',
        property: 'Property',
        status: 'Status',
        title: 'Inspection',
        type: 'Type',
      },
      complete: 'Complete',
      contractId: 'Contract ID',
      edit: 'Edit',
      empty: 'No inspections found.',
      error: 'Could not load inspections.',
      filters: 'Filters',
      includeArchived: 'Include archived',
      loading: 'Loading inspections...',
      pageDescription: 'Schedule inspections, execute checklists, and review completed reports.',
      pageTitle: 'Inspections',
      pendingOnly: 'Pending',
      propertyId: 'Property ID',
      restore: 'Restore',
      scheduledFrom: 'From date',
      scheduledTo: 'To date',
      search: 'Search inspections',
      searchPlaceholder: 'Search by title, property, resident, assignee, or status',
      start: 'Start',
      status: {
        archived: 'Archived',
        cancelled: 'Cancelled',
        completed: 'Completed',
        'in-progress': 'In progress',
        scheduled: 'Scheduled',
      } satisfies Record<InspectionStatus, string>,
      view: 'View details',
    },
    pagination: {
      next: 'Next',
      page: (page: number, totalPages: number) => `Page ${page} of ${totalPages}`,
      previous: 'Previous',
      range: (first: number, last: number, total: number) => `Showing ${first}-${last} of ${total}`,
    },
    terms: {
      conditionRatings: {
        attention: 'Attention',
        critical: 'Critical',
        damaged: 'Damaged',
        good: 'Good',
        'not-applicable': 'Not applicable',
        pending: 'Pending',
      } satisfies Record<InspectionConditionRating, string>,
      documentKinds: {
        attachment: 'Attachment',
        photo: 'Photo',
        report: 'Report',
        signature: 'Signature',
      } satisfies Record<InspectionDocumentKind, string>,
      none: 'Not informed',
      progress: (completed: number, total: number, percentage: number) =>
        `${completed}/${total} (${percentage}%)`,
      types: {
        inventory: 'Inventory',
        maintenance: 'Maintenance',
        'move-in': 'Move-in',
        'move-out': 'Move-out',
        other: 'Other',
        periodic: 'Periodic',
      } satisfies Record<InspectionType, string>,
    },
  },
  'pt-BR': {
    detail: {
      actions: {
        back: 'Voltar para vistorias',
        cancel: 'Cancelar',
        complete: 'Concluir',
        edit: 'Editar vistoria',
        save: 'Salvar',
        start: 'Iniciar',
      },
      audit: {
        archivedAt: 'Arquivada em',
        createdAt: 'Criada em',
        updatedAt: 'Atualizada em',
      },
      checklist: {
        add: 'Adicionar item',
        areaName: 'Area',
        conditionRating: 'Condicao',
        delete: 'Excluir',
        edit: 'Editar',
        empty: 'Nenhum item de checklist cadastrado.',
        save: 'Salvar item',
        itemName: 'Item',
        observations: 'Observacoes',
        required: 'Obrigatorio',
        title: 'Execucao do checklist',
      },
      completedReportTitle: 'Relatorio concluido',
      documentsTitle: 'Fotos e documentos',
      emptyRelationship: 'Este relacionamento aparecera aqui quando estiver conectado.',
      error: 'Nao foi possivel carregar os detalhes da vistoria.',
      labels: {
        assignee: 'Responsavel',
        cancelledAt: 'Cancelada em',
        cancellationReason: 'Motivo do cancelamento',
        completedAt: 'Concluida em',
        completionNotes: 'Observacoes da conclusao',
        contract: 'Contrato',
        notes: 'Observacoes',
        progress: 'Progresso',
        property: 'Imovel',
        resident: 'Morador',
        scheduledAt: 'Data agendada',
        startedAt: 'Iniciada em',
        status: 'Status',
        type: 'Tipo',
      },
      loading: 'Carregando detalhes da vistoria...',
      noNotes: 'Nenhuma observacao cadastrada.',
      pageDescription: 'Revise agenda, checklist, anexos, assinaturas e dados do relatorio.',
      relationshipTitle: 'Relacionamentos',
      relationships: {
        audit: 'Auditoria',
        timeline: 'Timeline',
      },
      signaturesTitle: 'Assinaturas',
      summaryTitle: 'Resumo da vistoria',
    },
    documentLink: {
      checklistItem: 'Item do checklist',
      documentId: 'ID do documento',
      kind: 'Tipo',
      label: 'Rotulo',
      link: 'Vincular documento',
      submit: 'Vincular',
      title: 'Vincular foto ou documento',
    },
    form: {
      assigneeRequired: 'Selecione o responsavel.',
      assignedUserId: 'Responsavel',
      cancel: 'Cancelar',
      contractId: 'Contrato',
      metadataSection: 'Agendamento',
      modeTitle: {
        create: 'Agendar vistoria',
        edit: 'Editar vistoria',
      },
      notes: 'Observacoes',
      propertyId: 'Imovel',
      propertyRequired: 'Selecione um imovel.',
      residentId: 'Morador',
      scheduledAt: 'Data agendada',
      scheduledAtRequired: 'Informe a data agendada.',
      signatureRole: 'Papel da assinatura',
      signatureRequired: 'Assinatura obrigatoria',
      signatureSection: 'Assinaturas',
      signatureSigner: 'Nome do assinante',
      submitCreate: 'Agendar vistoria',
      submitEdit: 'Salvar alteracoes',
      title: 'Titulo',
      type: 'Tipo',
      typeRequired: 'Selecione o tipo de vistoria.',
      validationTitle: 'Revise os campos destacados',
    },
    list: {
      activeFilters: (count: number) => `${count} filtros ativos`,
      add: 'Agendar vistoria',
      allStatuses: 'Todos',
      allTypes: 'Todos',
      archive: 'Arquivar',
      cancel: 'Cancelar',
      clearFilters: 'Limpar filtros',
      columns: {
        actions: 'Acoes',
        assignee: 'Responsavel',
        date: 'Data',
        progress: 'Progresso',
        property: 'Imovel',
        status: 'Status',
        title: 'Vistoria',
        type: 'Tipo',
      },
      complete: 'Concluir',
      contractId: 'ID do contrato',
      edit: 'Editar',
      empty: 'Nenhuma vistoria encontrada.',
      error: 'Nao foi possivel carregar as vistorias.',
      filters: 'Filtros',
      includeArchived: 'Incluir arquivadas',
      loading: 'Carregando vistorias...',
      pageDescription: 'Agende vistorias, execute checklists e revise relatorios concluidos.',
      pageTitle: 'Vistorias',
      pendingOnly: 'Pendentes',
      propertyId: 'ID do imovel',
      restore: 'Restaurar',
      scheduledFrom: 'Data inicial',
      scheduledTo: 'Data final',
      search: 'Buscar vistorias',
      searchPlaceholder: 'Busque por titulo, imovel, morador, responsavel ou status',
      start: 'Iniciar',
      status: {
        archived: 'Arquivada',
        cancelled: 'Cancelada',
        completed: 'Concluida',
        'in-progress': 'Em andamento',
        scheduled: 'Agendada',
      } satisfies Record<InspectionStatus, string>,
      view: 'Ver detalhes',
    },
    pagination: {
      next: 'Proxima',
      page: (page: number, totalPages: number) => `Pagina ${page} de ${totalPages}`,
      previous: 'Anterior',
      range: (first: number, last: number, total: number) =>
        `Exibindo ${first}-${last} de ${total}`,
    },
    terms: {
      conditionRatings: {
        attention: 'Atencao',
        critical: 'Critico',
        damaged: 'Danificado',
        good: 'Bom',
        'not-applicable': 'Nao se aplica',
        pending: 'Pendente',
      } satisfies Record<InspectionConditionRating, string>,
      documentKinds: {
        attachment: 'Anexo',
        photo: 'Foto',
        report: 'Relatorio',
        signature: 'Assinatura',
      } satisfies Record<InspectionDocumentKind, string>,
      none: 'Nao informado',
      progress: (completed: number, total: number, percentage: number) =>
        `${completed}/${total} (${percentage}%)`,
      types: {
        inventory: 'Inventario',
        maintenance: 'Manutencao',
        'move-in': 'Entrada',
        'move-out': 'Saida',
        other: 'Outra',
        periodic: 'Periodica',
      } satisfies Record<InspectionType, string>,
    },
  },
} as const

export function getInspectionCopy(locale: AppLocale) {
  return inspectionCopies[normalizeAppLocale(locale)]
}
