import { normalizeAppLocale, type AppLocale } from '../../i18n'
import type { PetAuthorizationStatus, PetDocumentKind, PetSpecies } from '../../lib/api/pets'

const petCopies = {
  'en-US': {
    detail: {
      actions: {
        authorize: 'Authorize',
        back: 'Back to pets',
        deny: 'Deny',
        edit: 'Edit pet',
      },
      audit: {
        archivedAt: 'Archived at',
        createdAt: 'Created at',
        updatedAt: 'Updated at',
      },
      documentsTitle: 'Documents',
      emptyRelationship: 'This relationship will appear here when connected.',
      error: 'Could not load pet details.',
      historyTitle: 'Authorization history',
      labels: {
        authorizationNotes: 'Authorization notes',
        authorizationStatus: 'Authorization',
        breed: 'Breed',
        contract: 'Contract',
        name: 'Name',
        notes: 'Notes',
        property: 'Property',
        resident: 'Resident',
        species: 'Species',
      },
      loading: 'Loading pet details...',
      noNotes: 'No notes registered.',
      pageDescription: 'Review owner, context, documents, authorization status, and history.',
      relationshipTitle: 'Relationships',
      relationships: {
        audit: 'Audit',
        timeline: 'Timeline',
      },
      summaryTitle: 'Pet summary',
    },
    form: {
      authorizationFormDocumentId: 'Authorization form document ID',
      authorizationNotes: 'Authorization notes',
      authorizationStatus: 'Authorization',
      authorizationStatusRequired: 'Select the authorization state.',
      breed: 'Breed',
      cancel: 'Cancel',
      contractId: 'Contract ID',
      contextSection: 'Owner and context',
      documentHint: 'Use the document ID until document picker integration is available.',
      documentsSection: 'Documents',
      modeTitle: {
        create: 'Create pet',
        edit: 'Edit pet',
      },
      name: 'Name',
      nameRequired: 'Enter the pet name.',
      notes: 'Notes',
      propertyId: 'Property ID',
      residentId: 'Resident ID',
      residentRequired: 'Enter the resident owner ID.',
      species: 'Species',
      speciesRequired: 'Select the species.',
      submitCreate: 'Create pet',
      submitEdit: 'Save changes',
      vaccinationRecordDocumentId: 'Vaccination record document ID',
      validationTitle: 'Review the highlighted fields',
    },
    list: {
      activeContractOnly: 'Active contract only',
      activeFilters: (count: number) => `${count} active filters`,
      add: 'Add pet',
      allSpecies: 'All',
      allStatuses: 'All',
      archive: 'Archive',
      authorize: 'Authorize',
      clearFilters: 'Clear filters',
      columns: {
        actions: 'Actions',
        authorization: 'Authorization',
        context: 'Context',
        owner: 'Owner',
        pet: 'Pet',
        species: 'Species',
      },
      contractId: 'Contract ID',
      deny: 'Deny',
      edit: 'Edit',
      empty: 'No pets found.',
      error: 'Could not load pets.',
      filters: 'Filters',
      includeArchived: 'Include archived',
      loading: 'Loading pets...',
      pageDescription: 'Manage resident pets, property context, documents, and authorization.',
      pageTitle: 'Pets',
      propertyId: 'Property ID',
      residentId: 'Resident ID',
      restore: 'Restore',
      search: 'Search pets',
      searchPlaceholder: 'Search by pet name, owner, property, species, or notes',
      status: {
        archived: 'Archived',
        authorized: 'Authorized',
        denied: 'Denied',
        inactive: 'Inactive',
        pending: 'Pending',
      } satisfies Record<PetAuthorizationStatus, string>,
      view: 'View details',
    },
    pagination: {
      next: 'Next',
      page: (page: number, totalPages: number) => `Page ${page} of ${totalPages}`,
      previous: 'Previous',
      range: (first: number, last: number, total: number) => `Showing ${first}-${last} of ${total}`,
    },
    terms: {
      documentKinds: {
        'authorization-form': 'Authorization form',
        'vaccination-record': 'Vaccination record',
      } satisfies Record<PetDocumentKind, string>,
      none: 'Not informed',
      species: {
        bird: 'Bird',
        cat: 'Cat',
        dog: 'Dog',
        fish: 'Fish',
        other: 'Other',
        rabbit: 'Rabbit',
        reptile: 'Reptile',
      } satisfies Record<PetSpecies, string>,
    },
  },
  'pt-BR': {
    detail: {
      actions: {
        authorize: 'Autorizar',
        back: 'Voltar para pets',
        deny: 'Negar',
        edit: 'Editar pet',
      },
      audit: {
        archivedAt: 'Arquivado em',
        createdAt: 'Criado em',
        updatedAt: 'Atualizado em',
      },
      documentsTitle: 'Documentos',
      emptyRelationship: 'Este relacionamento aparecera aqui quando estiver conectado.',
      error: 'Nao foi possivel carregar os detalhes do pet.',
      historyTitle: 'Historico de autorizacao',
      labels: {
        authorizationNotes: 'Observacoes da autorizacao',
        authorizationStatus: 'Autorizacao',
        breed: 'Raca',
        contract: 'Contrato',
        name: 'Nome',
        notes: 'Observacoes',
        property: 'Imovel',
        resident: 'Morador',
        species: 'Especie',
      },
      loading: 'Carregando detalhes do pet...',
      noNotes: 'Nenhuma observacao cadastrada.',
      pageDescription: 'Revise responsavel, contexto, documentos, autorizacao e historico.',
      relationshipTitle: 'Relacionamentos',
      relationships: {
        audit: 'Auditoria',
        timeline: 'Timeline',
      },
      summaryTitle: 'Resumo do pet',
    },
    form: {
      authorizationFormDocumentId: 'ID do formulario de autorizacao',
      authorizationNotes: 'Observacoes da autorizacao',
      authorizationStatus: 'Autorizacao',
      authorizationStatusRequired: 'Selecione o status de autorizacao.',
      breed: 'Raca',
      cancel: 'Cancelar',
      contractId: 'ID do contrato',
      contextSection: 'Responsavel e contexto',
      documentHint: 'Use o ID do documento ate a integracao com seletor de documentos.',
      documentsSection: 'Documentos',
      modeTitle: {
        create: 'Criar pet',
        edit: 'Editar pet',
      },
      name: 'Nome',
      nameRequired: 'Informe o nome do pet.',
      notes: 'Observacoes',
      propertyId: 'ID do imovel',
      residentId: 'ID do morador',
      residentRequired: 'Informe o ID do morador responsavel.',
      species: 'Especie',
      speciesRequired: 'Selecione a especie.',
      submitCreate: 'Criar pet',
      submitEdit: 'Salvar alteracoes',
      vaccinationRecordDocumentId: 'ID da carteira de vacinacao',
      validationTitle: 'Revise os campos destacados',
    },
    list: {
      activeContractOnly: 'Somente contrato ativo',
      activeFilters: (count: number) => `${count} filtros ativos`,
      add: 'Adicionar pet',
      allSpecies: 'Todas',
      allStatuses: 'Todos',
      archive: 'Arquivar',
      authorize: 'Autorizar',
      clearFilters: 'Limpar filtros',
      columns: {
        actions: 'Acoes',
        authorization: 'Autorizacao',
        context: 'Contexto',
        owner: 'Responsavel',
        pet: 'Pet',
        species: 'Especie',
      },
      contractId: 'ID do contrato',
      deny: 'Negar',
      edit: 'Editar',
      empty: 'Nenhum pet encontrado.',
      error: 'Nao foi possivel carregar os pets.',
      filters: 'Filtros',
      includeArchived: 'Incluir arquivados',
      loading: 'Carregando pets...',
      pageDescription: 'Gerencie pets de moradores, contexto do imovel, documentos e autorizacao.',
      pageTitle: 'Pets',
      propertyId: 'ID do imovel',
      residentId: 'ID do morador',
      restore: 'Restaurar',
      search: 'Buscar pets',
      searchPlaceholder: 'Busque por nome, morador, imovel, especie ou observacoes',
      status: {
        archived: 'Arquivado',
        authorized: 'Autorizado',
        denied: 'Negado',
        inactive: 'Inativo',
        pending: 'Pendente',
      } satisfies Record<PetAuthorizationStatus, string>,
      view: 'Ver detalhes',
    },
    pagination: {
      next: 'Proxima',
      page: (page: number, totalPages: number) => `Pagina ${page} de ${totalPages}`,
      previous: 'Anterior',
      range: (first: number, last: number, total: number) =>
        `Exibindo ${first}-${last} de ${total}`,
    },
    terms: {
      documentKinds: {
        'authorization-form': 'Formulario de autorizacao',
        'vaccination-record': 'Carteira de vacinacao',
      } satisfies Record<PetDocumentKind, string>,
      none: 'Nao informado',
      species: {
        bird: 'Ave',
        cat: 'Gato',
        dog: 'Cachorro',
        fish: 'Peixe',
        other: 'Outro',
        rabbit: 'Coelho',
        reptile: 'Reptil',
      } satisfies Record<PetSpecies, string>,
    },
  },
} as const

export function getPetCopy(locale: AppLocale) {
  return petCopies[normalizeAppLocale(locale)]
}
